### ISSUE TITLE
Font horizontal spacing issues

### ISSUE THREAD

**Issue by aolo2** [focus-editor/focus#10]
I'm trying out the linux build. It ran out of the box, so props for that! Most stuff is working as expected.
However, fonts are rendered *significally* different from what I would expect. For example here are screenshots of Roboto Mono Regular size 17 of the same line from Sublime (top) and Focus (bottom). The individual glyphs are the same, but the spacing is way too narrow.
![focus_ref2](https://user-images.githubusercontent.com/17429989/235903270-c3c23d6c-4ae0-4ed0-8036-f1dc2b94cd11.png)
![focus_ref](https://user-images.githubusercontent.com/17429989/235903274-c2fb42ae-ee97-4255-a33e-98ef5b100f5d.png)

**Comment by ileonte** [comment]
I suspect this is not Linux-specific. Can you please download the Windows `.exe` and run under Wine to see if font rendering is the same? (I suspect it is).

**Comment by focus-editor** [comment]
We're not adding that. I will read up on this and will fix this - didn't realise this was actually a requirement for monospaced fonts. Thanks @aolo2

**Comment by aolo2** [comment]
I looked into it, and I'm pretty sure it's not the problem. The font is monospaced, right, so no lsb. I think it is in fact an issue in Simp/font, not in focus.

**Comment by aolo2** [comment]
Maybe it's possible for you to ship a debug linux build so that I can step into it and compare with my own rasterizer?

**Comment by focus-editor** [comment]
I don't have the most recent debug build handy, but here's a relatively
recent one if that helps
https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv?usp=sharing

Maybe we're calculating `char_size` incorrectly - it's probably nothing to
do with rasterizing because we're just taking the font metrics Freetype
gives us, but will need to double check the code to make sure we're not
doing something wrong.

**Comment by aolo2** [comment]
Yes, I think your suspicion is correct. As I understand, `draw_code` assumes monspace font, and so takes in a single `char_size` parameter. If I understood the code correctly, this parameter should contain the *advance* value, but you clearly set `char_size` to `font.em_width`, which is just the approximate width of the glyph itself, not taking into account any empty space before and after the glyph.

To set the `char_size` correctly please refer to something like [FT_Get_Advance](https://freetype.org/freetype2/docs/reference/ft2-quick_advance.html) function from FreeType. For monospace fonts all glyphs have the same advance value. In fact, the truetype `hmtx` table only has a single record for monospaced fonts, see https://learn.microsoft.com/en-us/typography/opentype/spec/hmtx:

> As an optimization, the number of records can be less than the number of glyphs, in which case the advance width value of the last record applies to all remaining glyph IDs. This can be useful in monospaced fonts, or in fonts that have a large number of glyphs with the same advance width (provided the glyphs are ordered appropriately). 

This means that you can basically just request the advance width of any glyph (e.g. space) and use that as your `char_size`.

Hope this hepls, and feel free to ping me for further clarification if needed.

**Comment by focus-editor** [comment]
Thank you for your suggestion. I think I have fixed it now - please check the updated debug executable here https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv?usp=sharing.
