### ISSUE TITLE
Cannot scroll horizontally by selecting with the mouse sometimes

### ISSUE THREAD

**Issue by ostef** [focus-editor/focus#101]
It is not possible to scroll horizontally by selecting text with the mouse when the screen limits the movement of the mouse.

Currently the view scrolls only when the cursor is outside of it. There should probably be a threshold so the view scrolls when the cursor is near the inside bounds of the view instead of outside.

![focus-scroll-bug](https://github.com/focus-editor/focus/assets/47391841/200f2d6a-88de-4770-8533-f8b692007ed4)

 - OS: Windows 10
 - Focus Version: 0.1.10

**Comment by focus-editor** [comment]
Ouch. Never seen that before - due to the position of my monitors, there was always something on the left.

**Comment by focus-editor** [comment]
Should be fixed. Please reopen if it still persists.
