### ISSUE TITLE
Inputs not captured when searching for file. 

### ISSUE THREAD

**Issue by nilss0n** [focus-editor/focus#107]
When searching for a file in my workspace on macos (Cmd + P), all keyboard inputs are not captured.
Pressing '/' or '\' has no effect, which is somewhat annoying when you want to search for a specific path, e.g. "a/whatever" compared to "b/whatever".

For context, it's a macbook pro with a US physical keyboard layout. However, I'm from Sweden so I regularly switch layouts between Swe/US. Typing a '/' in the Swedish layout works just fine (Shift + 7), but pressing the '/' button (Button left of right shift) does nothing. Looking through the configs I can't find that the '/' and '\\' buttons are bound to anything. 

**To Reproduce**
1. Open a workspace on Macos
2. Press Cmd + P
3. Try to type '/'

**Expected behavior**
I expect the text input to capture everything I type. 

 - OS: Macos
 - Focus Version: 0.1.10

**Comment by cookednick** [comment]
Thank you for reporting. I was typing a long repy asking various questions, then it occured to me that you same Cmd + P and not Cmd + O. For the Cmd + P menu (files), we simply don't accept slashes as input. The search only occurs for filenames. If you want to open a file based on its directory, the Cmd + O menu is meant for that. Sorry that was confusing and that you expected it to work.

**Comment by cookednick** [comment]
Disregard my previous comment. I'll try this on my Mac later.

**Comment by ileonte** [comment]
I'm going to guess this has been fixed a while back. Please try with version `0.3.1` if you're still interested.
