### ISSUE TITLE
Text display with CJK font is weird

### ISSUE THREAD

**Issue by pebble2050** [focus-editor/focus#108]
**Describe the bug**

**To Reproduce**
0. Change the display font to NotoSans
1. Open focus editor
2. Ctrl+n 
3. こんにちは<enter>你好<enter>hello<enter>
4. the text "hello" display width is like CJK text, about 2 times for ASCII text.

**Expected behavior**
the text "hello" width as default font take

**Screenshots**
![image](https://github.com/focus-editor/focus/assets/47210889/0d122da2-0649-45e6-8a11-f19764365c03)

 - OS: [e.g. Windows]
- If on Linux - please specify whether you're on Wayland or X11
the latest release version on windows 10 

**Additional context**
left bottom text(default file name?) is messed.
And IME window is not at right place while typing.

**Comment by focus-editor** [comment]
I'm sorry, but Focus only supports monospaced fonts - it's an editor for code as its primary goal. We have no plans to support non-mono fonts in the foreseeable future - maybe we will add it someday, but other things will have priority for now.

The font used for file names doesn't have Japanese characters - this will be fixed at some point, but also this is low priority at the moment.

**Comment by pebble2050** [comment]
@focus-editor 
Thanks for reply.
CJK also has mono-spaced fonts,but the display is not as expected too.
Focus is such a good editor , It deserve for more users to try,
including the none English native programmers. 
Code maybe just English, but  comments with native language is a common needs.
Would you please reconsider it, Thanks.

**Comment by obiwanus** [comment]
There will be a way to override the default UI font in the future. Right now you'll only be able to do it if you have access to the compiler

**Comment by focus-editor** [comment]
> CJK also has mono-spaced fonts,but the display is not as expected too.
@pebble2050 please can you give an example and open another issue for it. We do want to support monospaced CJK fonts eventually.
