### ISSUE TITLE
Question: Vim mode?

### ISSUE THREAD

**Issue by ianyepan** [focus-editor/focus#120]
Will there be a vim-mode for modal editing in the future?

**Comment by focus-editor** [comment]
It's undecided. 

A full-blown vim-mode is unlikely (it's more likely to be implemented by someone else in their fork), but a basic modal editing support is possible. No ETA yet.

By the way you should be able to use https://github.com/focus-editor/focus/discussions for questions - please let us know if you can't.

**Comment by ianyepan** [comment]
Thanks!
