### ISSUE TITLE
Is there upcoming support for arm64 MacOS chips?

### ISSUE THREAD

**Issue by fostemi** [focus-editor/focus#125]
**Describe the bug**
There is no download for arm64 architecture and the M1 & M2 macOS chips.
**To Reproduce**
Using a M1 or M2 macOS you cannot run the editor.

**Expected behavior**
An executable for arm64 architecture.

 - OS: MacOS M2
 - Focus Version: 0.1.10

**Additional context**
Would love to see support and I'm willing to help raise a PR.

**Comment by focus-editor** [comment]
arm64 is low priority at the moment.

Did you try it on the M1/M2 and it didn't run?

**Comment by nikosaurusrex** [comment]
Running the editor works fine for me on MacOs with a M1

**Comment by fostemi** [comment]
Hi, 
It is working great now on a M2, I just wanted to know if there was going to be a different supported version for the new MacOS chips. I am closing this as it is not needed at the moment.
