### ISSUE TITLE
Ctrl-Space bound to show_commands inserts an errant space character

### ISSUE THREAD

**Issue by amasondev** [focus-editor/focus#133]
**Describe the bug**
Ctrl-Space bound to show_commands inserts an errant space character into the commands dialog. Seems to be the same Input module bug as Ctrl-Backspace.

**To Reproduce**
1. Configure Ctrl-Space to run show_commands in the global config file.
2. Press Ctrl-Space.
3. Begin typing "Switch", not that "Switch to Project" does not fuzzy match due to the extra space.

**Expected behavior**
No text input should carry over from a handled event.

 - OS: Windows
 - Focus Version: 0.2.0

**Additional context**
https://github.com/amasondev/focus/commit/efea945a92aaac70596bd80a4fd0091955d90776 my workaround.

**Comment by focus-editor** [comment]
Should be fixed here: https://github.com/focus-editor/focus/commit/5ad8c2b6c67ce30dfa6d2d67d6fc1f665d682e42. 

Thanks for the report.

Jon mentioned that the Input module needs a rewrite, so hopefully in the future things like this will be fixed in upstream as well
