### ISSUE TITLE
xdg_surface@972: error 3: xdg_surface has never been configured

### ISSUE THREAD

**Issue by GlennMm** [focus-editor/focus#134]
Tries downloaded linux version, and tried to run it via terminal and i got this error xdg_surface@972: error 3: xdg_surface has never been configured 

OS: Arch Linux
WM: hyprland (wayland based)
Focus Version: 0.2.0

**Comment by valignatev** [comment]
I have the same issue on sway. Seem like something related to wl-roots, because the editor is confirmed to work in KDE's wayland compositor (kwin)

**Comment by ileonte** [comment]
Works fine on my machine (Hyprland 0.28.0, Focus 0.2.0).
@GlennMm what graphics card do you have?

**Comment by ileonte** [comment]
Please re-test with this binary: https://ileonte.dev/focus-builds/dev/focus-linux-dev-ef3f3af

**Comment by GlennMm** [comment]
Thank you @ileonte the binary you provided is opening. but the binary on the github release is giving the error i gave. Im using an old laptop it has this gpu Intel 2nd Genereation Core Processor Family.

**Comment by GlennMm** [comment]
i also did @valignatev set FOCUS_LD_BACKEND=x11 the binary from github release page opened.

**Comment by GlennMm** [comment]
You are welcome @ileonte
