### ISSUE TITLE
Suggestion: General support for syntax highlighting

### ISSUE THREAD

**Issue by Hyouteki** [focus-editor/focus#135]
We can create a JSON file for syntax highlighting. It can be a JSON object array where each object is a name of a programming language.<br>
Example:
``` json
[ 
    "c": {
        "keyword": ["static", "const", "if", "else", "break", "#include"],
        "datatype": ["void", "int", "char", "double"],
    },
    "python": {
        "keyword": ["def", "import", "if", "else", "break"],
        "datatype": ["char", "int", "str", "double"],
    },
]
```
Whenever we encounter a keyword or a datatype we can color that word with keyword or datatype specific color.<br>
There are quite a few limitations with this approach;
- This approach might not be adaptable with the current logic of text rendering.
- Each language have different way of representing comment(singleline/multiline). One solution that comes to my mind is to add keys for "comment".<br><br>
    ``` json
    "c": {
        "keyword": ["static", "const", "if", "else", "break", "#include"],
        "datatype": ["void", "int", "char", "double"],
        "singleline-comment": ["//"],
        "multiline-comment": ["/**/"]
    }
    ```
- There can be some language specific words that has to be handled differently.
 
Benefits;
- Easy support for a new language.
- Easily customizable by user.

**Comment by focus-editor** [comment]
Something like this is planned: #105

**Comment by Hyouteki** [comment]
Oh, yes thanks
