### ISSUE TITLE
Launching from command line to just quickly check out a file scans whole directory structure.

### ISSUE THREAD

**Issue by mcourteaux** [focus-editor/focus#14]
When I try to do: `./focus /home/martijn/demo.cpp`, it spends about a minute scanning my home folder, installing directory watchers.

I don't know the philosophy regarding projects and where this editor fits in besides projects, but this seems not ideal.

**Comment by focus-editor** [comment]
I will investigate why it takes a minute because it shouldn't scan the folder in the sense of adding it to the workspace, and I wouldn't expect the file watcher to take a minute to add a directory (but maybe it could be the way it's done on Linux).

Currently this is how the watching of individual files is implemented - the file watcher module in Jai doesn't seem to provide the ability to watch files, only folders, this is why the parent folder is added to the file watcher.

**Comment by mcourteaux** [comment]
It traverses all folder and subfolders to full depth, if that helps. It also reports a bunch of folders it can't watch, that's why I realized. Here is a snippet of the output when I try to open a file in my home folder:

![image](https://user-images.githubusercontent.com/845012/235993056-31fe553f-4bf8-4d09-bed0-e1d331e2f300.png)

**Comment by mcourteaux** [comment]
Regarding what I said "I don't know the philosophy". Maybe it only makes sense to do the file watching if you have an actual project config setup?

**Comment by focus-editor** [comment]
This would be inconsistent - why would the editor not react to changes made to individual files outside of the editor when there's no project setup? Also, the editor doesn't really care if you have a project or not. You could just add your project dirs to the global config if you want and it would behave exactly the same.

The correct solution to this would be to implement a way to watch individual files in a more efficient way. I will definitely explore the options when I get to this issue

**Comment by mcourteaux** [comment]
Aha. I see! Makes sense. Thanks for clarifying. I like spending some time discussing issues in open source projects! I always appreciate it when my ideas are taken seriously. :smile: Keep up the nice work!

**Comment by focus-editor** [comment]
This might be fixed in the next release (`0.2.0`)

When it's out please test again.
