### ISSUE TITLE
Bug: Focus crashes when trying to drag and drop a file inside the editor on Linux

### ISSUE THREAD

**Issue by rilysh** [focus-editor/focus#147]
**Describe the bug**
Hi,
On Linux, when I try to drag and drop a file inside focus, it instantly crashes with a segfault.

**To Reproduce**
1. Grab focus editor build [0.2.0](https://github.com/focus-editor/focus/releases/tag/0.2.0) from GitHub releases
2. Launch focus and drop a file inside the editor (drag and drop)
3. Focus will crash with a segfault

**Expected behavior**
Focus shall not crash, if drag and drop is unsupported under Linux, a popup message box is good enough to let the user know about it.

 - OS: Debian 12, with X11
 - Focus Version: 0.2.0-dev

**Additional context**
Running focus under GDB, it seems like the segfault is coming from this function. https://github.com/focus-editor/focus/blob/28c52f9dbb20b112cb3835adcbd29f703744993c/modules/Input/module.jai#L220
especially on that event handling when targetting OS isn't Windows. I can be wrong on this point, however.

**Comment by focus-editor** [comment]
Reproduced on Windows too. Thanks for the report!

**Comment by valignatev** [comment]
At least on linux this is fixed in https://github.com/focus-editor/focus/commit/6bfdb0c0f827cfffba0c96cbb3a75d370ef984c6

**Comment by ileonte** [comment]
Closing this, please use the nightly builds until the next official release.
