### ISSUE TITLE
Comping with -x64 and - release cause scroll not to work.

### ISSUE THREAD

**Issue by mcourteaux** [focus-editor/focus#15]
I am experimenting a little, and compiling like this:

```sh
~/focus
❯ ~/Downloads/jai/bin/jai-linux -x64 first.jai - release

```

Works fine, but when opening a file, I can't scroll. That's a very strange bug to report -- I know, but it seems to be consistent.

Also, pressing `j` on the keyboard, seems to replace the whole file by a bunch of `i`:

![image](https://user-images.githubusercontent.com/845012/235947124-392a5ab0-cb42-4a65-995b-fe566c74c9e3.png)

I hope you can reproduce this.

----
❯ ~/Downloads/jai/bin/jai-linux -version
Version: beta 0.1.061, built on 16 April 2023.

**Comment by ileonte** [comment]
Please try compiling with Jai 0.1.62 (I'm surprised it even built with 061).

**Comment by mcourteaux** [comment]
Just tried it with Jai 0.1.62. Different machine *exact* same result.

**Comment by cookednick** [comment]
This occurs in both debug and release mode, on macOS as well, and it is a compiler bug. I have reported it. Will close this issue when it is fixed.

**Comment by ileonte** [comment]
I'm closing this issue, not much we can do about it. This still seems broken in the latest compiler, seems like it's not a priority fix.

**Comment by mcourteaux** [comment]
It's been a while since I did Jai, but how is this a compiler bug? libc `memcpy` is not supposed to be used with overlapping ranges. Does Jai's `memcpy` have different semantics than libc's?

I checked `Preload.jai`, and there is no documentation for this function, and there is no equivalent `memmove` it seems... I guess that explains...

**Comment by ileonte** [comment]
`memcpy` is not the `libc` one, it is defined as an intrinsic which means that the compiler is the one that decides what it actually does. This intrinsic behavior is different between the `x64` and `llvm` backends of the compiler, which is what's causing this bug.
