### ISSUE TITLE
Feature Request, 'move_viewport_center_to_cursor'

### ISSUE THREAD

**Issue by alpergkcan** [focus-editor/focus#150]
I see that default global config has the following keybind:
`Alt-V             move_cursor_to_viewport_center`
which does what it says 😄 and it has some nice use cases, 
but I will make a feature request for exact opposite of this behavior that is similar to the emacs default bind "Ctrl-L" doing 'move_viewport_center_to_cursor' that is also useful and might be a nice addition for the editor.

**Comment by RednibCoding** [comment]
When the cursor is offscreen, one can just press `escape` to jump back to the cursor position.

**Comment by alpergkcan** [comment]
`escape` is not what I requested as it does not center it, and has no bindable action if i'm not missing something

**Comment by focus-editor** [comment]
The command is already there, it's called `center_viewport_on_cursor`
