### ISSUE TITLE
Typing path with direct match

### ISSUE THREAD

**Issue by SamHSmith** [focus-editor/focus#16]
When typing '/' in the file opener the top result in the list is selected. The bug is that there can be an exact match in the list but this directory is not opened. Basically, typing a slash should not autocomplete when there is an exact match.

**Comment by ileonte** [comment]
Please try the following: in the `[open file dialog]` section of the config file comment out the line that reads `/    open_directory` and see if that makes it work as you expect.

**Comment by focus-editor** [comment]
This is a valid issue. It will be fixed. Thanks

**Comment by cookednick** [comment]
Just fixed this. "/" (not "\") will open "/" if it is in the list. If it is not in the list, it will open the currently-selected directory like before. A special case was added, in other words. This will ship with the next release.
