### ISSUE TITLE
Showstoppers and suggestions

### ISSUE THREAD

**Issue by Gavin-Holt** [focus-editor/focus#160]
Hi,

I have been looking at different editors for some time, call it a hobby.

Focus is really nice, intrinsically portable across OS, and as a portable application on my One Drive.

From my experience so far, Focus has some great features, but also some real showstoppers.

# Showstoppers

## No replace function?

Sorry, I can't find a text replace function. Neither can I find a _multi-cursor select all occurrences_ function to achieve similar.

Editing without _replace_ is untenable.

## EOL Preservation

Surely it's a simple routine to save files with EOL bytes the same as when the file was opened?

Some files are altered in several different editors, depending upon context, and messing with the EOL bytes causes havoc in a Windows environment.

# Nice features

## search_in_buffer_dropdown_mode

This is a really useful action. In other editors, I use fzf.exe to get a line number and achieve the same functionality:

## Mouse wheel zoom

I work using a TV as a monitor, zooming is really helpful.

## Highlight all matches

This is super helpful.

## Cursor position indicator

Coming from a terminal editor, the cursor is a joy. I prefer an I-beam (cursor_as_block:false) and the way I can see it at the end of a selection is great.

## Keyboard mappings

Focus comes very close to my own preferred keyboard mapping. With the configuration file, I have managed to remap the differences, limited by the available functionality.

## Drag and drop

Although I prefer the keyboard, it can be convenient to drop a file from the Windows file Explorer onto an editor window  - thank you.

## Graphical rendering

Focus is really fast to load, and may tempt me away from terminal based editing (Micro,FTE). The rendering is beautiful and a wide variety of colours are available. The pop-up lists are self filtering and very responsive.

Does the rendering engine offer the ability to underline? This would allow live spell-checking with squiggly underlines, or similar for suspected syntax errors. If Focus can provide this type of visible feedback, then there are many posibilities in the future, especially with LSP providers to offload computation.

# Suggestions

I know you want to keep it simple, so please feel free to ignore all the following :) 

## Animation

I hate animation. It is not in keeping with a fast, distraction free editing experience. Smooth scrolling yes, everything else no!

## No redraw during resize

When I drag the edge of the window to resize, the content goes blank!

## Colour configuration

Could the syntax highlighter for ```focus-config``` files display the colour codes in the coded colour? This would allow us to play with the colours much more easily. 

## Command line location

I prefer to enter all commands/search text at the bottom left of the buffer screen (using 100% width) with pop-up lists instead of dropdowns. This appears more consistent, and avoids any distraction from text around the input field.

## Incomplete Command List

There are many _bindable_ functions not present in the command selector. This limits discoverability:

* Move to buffer: This is especially difficult as there is no visible indicator that other buffers are open. The first time I dragged and dropped onto an open buffer, I though I had lost my work. I would prefer a circular path for move_to_previous_buffer / move_to_next_buffer, excluding the welcome screen.

* Close welcome screen: If I close each buffer separately, I end up at the welcome screen. I would prefer that closing last buffer exits the application, or at least that ```close_current_editor``` closes the welcome screen. I prefer a fuzzy find pop-up to switch between buffers (Alt-w).
 
* Quit: There is no ```Quit``` or ```Exit``` in the command selector. Isn't there another editor pilloried for un-discoverable exit command?

Kind Regards Gavin Holt

**Comment by focus-editor** [comment]
Thanks for the detailed feedback. The main limiting factor for making the editor better is time - we're busy and progress is slow. But we'll get there.

There will be a replace command, it's not at the top of the list yet. One could use the select all occurrences as a workaround for now.

We'll consider retaining CRLF on save.

> I hate animation
`disable_file_open_close_animations` is an option for you.

> No redraw during resize
We used to have this but removed it because it's tricky to implement without causing issues. It will be done but it's low priority

> Colour configuration etc
Have a look at a fork by @onelivesleft - https://github.com/onelivesleft/focus - he's implemented a ton of things on top of the base editor. By the way, people are encouraged to do that with this editor, as we don't intend to try to accommodate everyone's request like VSCode does

**Comment by Gavin-Holt** [comment]
Hi,

Many thanks for your comments. I will look forward to the next release. Reviewing the fork you mentioned, it's not stable enough to use, but I am interested in ```add_cursors_to_line_ends``` and ```add_cursors_to_line_starts```. 

A little more experimenting prompted the following ideas:

1. Escape 

    Adding a keymap section for the command dialog:

    ```
    [command dialog]
    Escape      close_dialog
    ```

    Would allow me to assign
    
    ```
    [editor]
    Escape      quit
    Alt-c       remove_additional_cursors 
    ```

2. Ctrl-K

    I would prefer that ```delete_to_end_of_line``` and ```delete_to_start_of_line``` not alter the clipboard. Would you consider different commands to cut these segments: ```cut_to_end_of_line``` and ```cut_to_start_of_line```?

I will watch and wait, sorry I can't contribute solutions - I describe myself as a non-compiling user - and software is not my day job.

Kind Regards Gavin Holt 
P.S. My [global.focus-config](https://github.com/focus-editor/focus/files/12508225/global.txt)
