### ISSUE TITLE
Feature request: binaries for macOS arm64

### ISSUE THREAD

**Issue by julien** [focus-editor/focus#166]
I was wondering if it would be possible to have binaries for macOS arm64 in the releases.

The currency version requires "Rosetta".

Thanks.

**Comment by ileonte** [comment]
Unfortunately the Jai compiler only supports x86_64 at the moment.

**Comment by julien** [comment]
Hey @ileonte thanks for the quick reply. 

I guess I'll just have to wait.
I'll close this to avoid the noise.
