### ISSUE TITLE
BUG: Undo/Redo

### ISSUE THREAD

**Issue by onelivesleft** [focus-editor/focus#180]
When performing a redo, focus will redo the change then jump the cursor to the next redo position, meaning the user gets no feedback on the change being applied.  Better behaviour for redo would be to place cursor at just performed redo, not at site of next potential redo.

**Comment by focus-editor** [comment]
That's true, thanks for reporting

**Comment by focus-editor** [comment]
Hopefully this particular issue is now resolved

**Comment by IRooc** [comment]
When there is nothing to undo yet in a file, the cursor now jumps to the top of the file. This should not happen instead nothing should happen if there is nothing to undo yet.

**Comment by obiwanus** [comment]
@IRooc it felt like the right thing to do when I was working on it. Please let's discuss on discord why this is a problem and if there's indeed a problem we'll remove it. That way others can chip in as well
