### ISSUE TITLE
Behaviour: double-click + drag

### ISSUE THREAD

**Issue by onelivesleft** [focus-editor/focus#189]
Proviso: this may be Windows-centric.

Normal behaviour in most applications seems to be, if the user double clicks a word the word is selected (which Focus does), and if the user then drags to a side onto another word, the next word is selected, and so on for as far as the mouse moves.  Currently Focus will select the word you double-click, but then simply set the selection to the position the cursor is at, be it mid-word or w/e.

**Comment by flysand7** [comment]
> Proviso: this may be Windows-centric

As a sublime user on linux, +1 for making this behaviour work

**Comment by focus-editor** [comment]
This has been fixed for a while now
