### ISSUE TITLE
Potential race condition when opening a new empty buffer? 

### ISSUE THREAD

**Issue by StevenSavold** [focus-editor/focus#20]
**Describe the bug**
It feels like there is a race condition when opening new empty buffers. When using Ctrl+N I will sometimes get a new empty buffer (expected), sometimes get a buffer with a random file from within my workspace directories (unexpected), and other times will get a crash (unexpected).

**To Reproduce**
1. Open the editor `.\focus.exe`
2. Open a new empty buffer `Ctrl+N`
3. If you get a valid empty buffer, type a few characters into the buffer and repeat from step 2 until you see the strange behavior

**Expected behavior**
A new empty buffer is created every time

**Screenshots**
N/A

 - OS: Windows
 - Focus Version: Latest commit (hash: 5e8ecee5c69198e741d4eca73d7d2e5d010c75d6)

**Additional context**
Here is the stack trace from when it crashes:
```
Array bounds check failed. (The attempted index is 0, but the array has dimension 0, so no index is valid). Site is L:/Dev/Third-Party/focus/src/buffer.jai:109.
Panic.
A breakpoint was hit, but no debugger is attached.

Printing the stack trace:
handle_exception                  F:\tools\Jai\jai-beta-1-062\modules\Runtime_Support_Crash_Handler.jai:363
... (skipping OS-internal procedures)
debug_break                       L:\Dev\Third-Party\focus\modules\Runtime_Support.jai:12
my_panic                          L:\Dev\Third-Party\focus\modules\Runtime_Support.jai:143
__array_bounds_check_fail         L:\Dev\Third-Party\focus\modules\Runtime_Support.jai:196
offset_to_coords                  L:\Dev\Third-Party\focus\src\buffer.jai:109
get_cursor_coords                 L:\Dev\Third-Party\focus\src\buffer.jai:125
draw_editor                       L:\Dev\Third-Party\focus\src\draw.jai:368
draw_frame                        L:\Dev\Third-Party\focus\src\draw.jai:21
main                              L:\Dev\Third-Party\focus\src\main.jai:228
```

The crash seems to be from the editor attempting to draw the buffer before the initialization code can add the first line to `line_starts`? But what is stranger to me, is when the buffer opens but is loaded with the content of a random file in my workspace directories.

**Comment by StevenSavold** [comment]
I'd be happy to implement a fix, I just need more time to get to the bottom of what exactly is happening

**Comment by focus-editor** [comment]
This is very weird. There's no threading involved, so it must be something to do with the order of operations. If you can look into it further that'll be great. Thanks

**Comment by StevenSavold** [comment]
I saw a mutex being initialized when making a new buffer, so I assumed maybe a threaded context. I will absolutely look into this further though 😄

**Comment by focus-editor** [comment]
The mutex needs to be held by the main thread when making changes to the buffer contents, because the search threads may try to read the same content at the same time.

The same mutex needs to be held by the search threads when they attempt to read buffer contents for the above reason.

The main thread doesn't need to hold the mutex while reading buffer contents, because there are no other writers other than the main thread.

**Comment by StevenSavold** [comment]
My current theory is that the bug lies with the `open_buffers` bucket array. Perhaps the function that is making a new empty buffer is conflicting with a thread that is opening buffers for search purposes? That might explain the weird random file content I was seeing...

**Comment by focus-editor** [comment]
No threads should ever call the `editors_open_file()` function, which can create a new buffer. Also, your repro didn't include searching for anything (I couldn't reproduce it, by the way). And if you don't search, then the search threadproc will never run. Still, it's definitely possible that the bug is within the bucket array.

**Comment by focus-editor** [comment]
Actually I'm wrong. The initial workspace scanner is a thread which calls this function. Sorry for misleading you - it's the end of the day for me and I can't think properly 😅 . I think this is exactly what happens.

**Comment by StevenSavold** [comment]
So my default workspace is probably unusually large (it has over 45,000 files). So it takes just over a minute to load all the files. During that time is when I see the bug. If I let that minute or so pass and the workspace scanner is done working, I get the correct behavior (which probably explains why you couldn't repro).

I have not yet been successful in getting the bug to go away. I'm thinking now that it has more to do with the editor that was created to hold the new empty buffer being modified by a workspace scanning thread accidentally, before we can get around to rendering it. I'll be busy over the next couple days, but will continue my bug hunting after that. If you happen to catch it before I can let me know 😄

**Comment by StevenSavold** [comment]
So, actually I think I found it. When the new empty buffer is being made, focus will scan the open buffers for an already existing empty buffer. But the buffers being created by the workspace scanner might not have yet had the path and content populated yet. So we accidentally find an "empty" buffer, which in a separate thread will get populated shortly after. 

It seems by extending the critical sections in `find_or_create_buffer` and `find_or_create_an_empty_buffer` to be the whole function will solve the issue. However, I am not sure if extending these sections to be that long is really the best option. For now I will open a PR with my changes and I'll let you decide if you would rather have a different solution.
