### ISSUE TITLE
saving file issue

### ISSUE THREAD

**Issue by CyanMARgh** [focus-editor/focus#201]
**Describe the bug**
When saving a new file using ctrl+s, a path entry window opens without displaying the hierarchical structure (as, for example, when opening a file). If you leave the field blank and press Enter, focus crashes with the following error:
```
Assertion failed in file /build/src/files.jai at line 2, char 5: 
Trying to get file info from a non-absolute path. This is a bug.
```
**To Reproduce**
open focus
Ctrl+N
Ctrl+S
Enter

**Expected behavior**

After Enter, focus should prevent the user from saving the file and possibly notify the user with a pop-up message at the bottom right. In the best case, after ctrl+s a window should appear similar to the one that opens with ctrl+o.

**Screenshots**
![example](https://github.com/focus-editor/focus/assets/66627948/4bd306ef-9284-4ca9-b250-c94450209a08)

- OS: Linux, ubuntu 22.04.2 LTS; X11
- Focus Version: 0.2.0-dev / 11 Aughust 2023, 14:45:46

**Comment by ileonte** [comment]
That build is very old, the save dialog has been rewritten since then. Please try the latest "nightly" build: https://ileonte.dev/focus-builds/Linux/nightly/focus-linux-nightly-42b3aa8

**Comment by CyanMARgh** [comment]
no bug in this version, thanks
