### ISSUE TITLE
Typing `/` doesn't do anything in file search

### ISSUE THREAD

**Issue by flysand7** [focus-editor/focus#203]
**Describe the bug**
When hit ctrl-p and typing `/` nothing happens

**To Reproduce**
1. Hit ctrl-p to open file search (default config)
2. Type `/`

**Expected behavior**
When `/` typed, it appears in the search box and the string is matched against path

**Additional context**
Arch linux on x11.

**Comment by SentientCoffee** [comment]
Just spent a little bit debugging this. It seems that on Windows, for the "/" keypress, it does not trigger a `TEXT_INPUT` event, while on Linux it does. This causes `num_text_inputs_to_ignore` in the `for event : Input.events_this_frame` loop to increase on Linux, thus the behaviour above.
