### ISSUE TITLE
Save as, fuzzy match

### ISSUE THREAD

**Issue by filippocrocchini** [focus-editor/focus#208]
When saving a new file I can only override an existing file if any of the files in the target folder fuzzy matches to the new file name.

In my version I just hacked a solution together. I believe the issue is that open_file_dialog does not allow to _not_ select an entry. So, if there is anything in the list after fuzzy matching, you can't do anything but pick one even if neither of them is a perfect match.

A couple of solutions I considered are adding an artificial entry if the mode is .save_as and there's no perfect match, and ignoring the selected entry if you try to open one that wasn't a perfect match.

**Comment by ileonte** [comment]
This should now be implemented, please test with the latest changes on `main`.
