### ISSUE TITLE
Word delete (CTRL + Backspace) stops at accented and non-English letters

### ISSUE THREAD

**Issue by fbjerno** [focus-editor/focus#212]
**Describe the bug**
When attempting to delete a whole word using CTRL + Backspace (or CTRL + DEL), the deletion stops at non-English letters such as 'ö', 'æ', 'é' or 'ç'.

For example, performing a word delete on the word "exposé" will work the following way:
exposé CTRL + Backspace -> expos
CTRL + DEL exposé -> é

This also applies the other way around, that is to say:
öäåabc CTRL + Backspace -> öäå
CTRL + DEL öäåabc -> abc

Numbers are treated the same way as English letters:
öäåabc123 CTRL + Backspace -> öäå
CTRL + DEL öäåabc123 -> abc123

**To Reproduce**
1. Type a word or some sequence of letters which includes a non-English letter
2. Place the cursor at the end of the the word/sequence and press CTRL + Backspace
3. If the first character to be deleted is an English letter or a number, all characters up until any non-English letter/number will be deleted
    Otherwise (if the first character to be deleted is a non-English letter), all characters up until any English letter/number will be deleted

**Expected behavior**
The entire sequence of characters is deleted.

 - OS:  Windows
 - Focus Version: 0.2.0

**Comment by focus-editor** [comment]
This is easily fixable, but we need a list of most common chars and rules on how to check for them https://github.com/focus-editor/focus/blob/de41c1345c36d3a8127bb89771fe8c5cc7321b70/src/utils.jai#L256

**Comment by fbjerno** [comment]
I assume files are encoded in UTF-8, right? Not an expert on Unicode or text formatting but if we're only considering variants of Latin letters, it seems including the letter parts of the Unicode block "Latin-1 Supplement" as well as the blocks "Latin Extended-A" and "Latin Extended-B" would solve this problem:

```
// Latin-1 Supplement
(#char "À" <= ch && ch <= #char "Ö") || (#char "Ø" <= ch && ch <= #char "ö") || (#char "ø" <= ch && ch <= #char "ÿ") ||
// Latin Extended-A
(#char "Ā" <= ch && ch <= #char "ſ") ||
// Latin Extended-B
(#char "ƀ" <= ch && ch <= #char "ɏ")
```
https://en.wikipedia.org/wiki/Unicode_block

For other languages, you would do more or less the same with all the language related blocks in the Basic Multilingual Plane (all Unicode characters that can be stored in 2 bytes). You could filter out all irrelevant blocks (such as mathematical operators) and then collapse all contiguous blocks into single range checks. This is assuming there aren't any "non-letter" characters within these blocks (which there are in Latin-1 Supplement, for example).

**Comment by ileonte** [comment]
I think the way this should work is that instead of having a list of "valid word characters" we should have a list of all UTF whitespace characters (fixed) plus a list of language-specific word break characters (populated from the active language highlighter); then every char NOT in these two lists being considered a "word" character.

**Comment by focus-editor** [comment]
@ileonte good suggestion. Would you like to submit a PR?

**Comment by ileonte** [comment]
Yes, I will look into it.

**Comment by ileonte** [comment]
@fbjerno in case you're not in the Jai beta you can grad the pre-built binary that should have this fixed from here: https://ileonte.dev/focus-builds/Windows/nightly/focus-nightly-6403175.exe

**Comment by fbjerno** [comment]
That's very thoughtful of you, thank you!
