### ISSUE TITLE
Jai Syntax Highlighting: HERE strings appear valid when they are not.

### ISSUE THREAD

**Issue by cookednick** [focus-editor/focus#213]
This currently highlights as if it works and makes sense:
```
#import "Basic";

main :: () {
    print(#string HERE
This is a string. HERE);
    x := 0; // This is not highlighted as part of the HERE string, even though the compiler considers it to be.
}
```
When running this code in the compiler, it gave an error that was like "Reached end of file without ever terminating HERE string." In other words, HERE string end-tokens are only valid at the beginning of a line.

**Comment by focus-editor** [comment]
Decided it's not worth it to put a strain on the highlighter. Our highlighters in their current state are not smart, and that's intended.
