### ISSUE TITLE
Application works in MacOS Mojave, but you have to open the binary inside the app package

### ISSUE THREAD

**Issue by differenceclouds** [focus-editor/focus#232]
The application seems to work fine on my old version of macOS (10.14), but not by double-clicking the .app package. I can open the binary inside the package however. I tried fiddling with the .plist file, but to no avail.

That, plus retina support, and this editor is looking pretty good. thanks for your work!

**Comment by focus-editor** [comment]
Maybe @cookednick knows why the app double click might not work?

**Comment by diimdeep** [comment]
Trying to add min version to .plist doesn't help

```
        <key>CFBundleSupportedPlatforms</key>
        <array>
            <string>MacOSX</string>
        </array>
        <key>LSMinimumSystemVersion</key>
        <string>10.11</string>
```

Min version is being set in binary.

`otool -l focus`
```
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 12.0
      sdk 12.0
   ntools 1
     tool 3
  version 1022.1
```

https://stackoverflow.com/questions/17143373/determine-minimum-osx-version-a-binary-was-compiled-for
https://stackoverflow.com/questions/39310079/mac-app-package-backwards-compatibility-error-you-cant-use-this-version-of-t/39688949#39688949

**Comment by diimdeep** [comment]
fix `vtool -set-build-version macos 11.0 11.0 -replace -output  /Applications/Focus.app/Contents/MacOS/Focus /Applications/Focus.app/Contents/MacOS/Focus`

**Comment by cookednick** [comment]
> Maybe @cookednick knows why the app double click might not work?

I just enabled GitHub email notifications. I found this issue by accident just now.

@diimdeep Could you please try [this version](https://github.com/focus-editor/focus/files/14118524/Focus-0.3.1-72c5015-Intel.dmg.zip) and see if the issue is resolved? I changed the minimum to 10.14 within the binary. If you say it works, I will commit it to the main branch for future releases.

**Comment by cookednick** [comment]
> Trying to add min version to .plist doesn't help
> 
> ```
>         <key>CFBundleSupportedPlatforms</key>
>         <array>
>             <string>MacOSX</string>
>         </array>
>         <key>LSMinimumSystemVersion</key>
>         <string>10.11</string>
> ```

I read the documentation for `LSMinimumSystemVersion` and it seems like it's only relevant for the App Store.

**Comment by differenceclouds** [comment]
The linked version seems to be working fine, thanks!

**Comment by cookednick** [comment]
Excellent! Added to the next release.
