### ISSUE TITLE
add cursors to line starts crashes on EOF

### ISSUE THREAD

**Issue by Sanian-Creations** [focus-editor/focus#248]
### Bug description
The command "Add Cursors To Line Starts" does not work properly (it can delete the cursor that is there) on the last line of a file and can trigger an assert in some circumstances.

### Repro
1. open a new file
2. insert a single newline
3. run the command "Add Cursors To Line Starts" (or "Ends")

**Comment by focus-editor** [comment]
Please check if there are still issues with this. Thanks
