### ISSUE TITLE
Editor cannot find fonts under linux

### ISSUE THREAD

**Issue by natefusion** [focus-editor/focus#25]
From this error message:
![Screenshot_20230504_183728](https://user-images.githubusercontent.com/47067814/236347281-e14d3375-7d7a-441a-a18f-d761f9f04919.png)
The editor only looked in /usr/share/fonts, but this is what my /usr/share/fonts directory looks like:

![Screenshot_20230504_185715](https://user-images.githubusercontent.com/47067814/236347478-cf81f9ec-a9a4-4c21-a417-8b09bc128f69.png)

The font I wanted was located in /usr/share/fonts/TTF.

**Comment by focus-editor** [comment]
You can provide a full path to the font file as a workaround for now

**Comment by natefusion** [comment]
Thanks, that works.

**Comment by aolo2** [comment]
Not sure if you want to expand the dependencies for this, but the "standart" way of finding fonts on Linux seems to be through fontconfig. In the command line you do it using utilities like `fc-match`, which accept a "font name" and find the best matching font file.

**Comment by SamHSmith** [comment]
I think that is a very bad idea. I think the only sensible thing is to give a full or exe relative path.

**Comment by focus-editor** [comment]
I've expanded the error message to let the user know they can provide a full path to the font they want. This should be a decent enough solution to avoid depending on external commands.

**Comment by ileonte** [comment]
As of version `0.1.9` you can simply say `font: jetbrains mono` in the config file and the editor should find the correct file path for that font face (we now use `libfontconfig` to match font face names to font files that have been installed in the system).
