### ISSUE TITLE
Some fonts are really small

### ISSUE THREAD

**Issue by everlyy** [focus-editor/focus#251]
**Describe the bug**
A bunch of the fonts are really small even though I've set my font size to 24.
The only font that doesn't seem to be affected is the font of the text editor itself, the rest (command palette, bar in the bottom, etc.) are all in a way tinier, almost unreadable font

**To Reproduce**
Don't exactly know why this happened, it's just been like this since I first launched it.

**Expected behavior**
I expect all the fonts to be the same size, respecting the font size I set in my config.

**Screenshots**
This screenshot shows the font in the editor being the right size, but the command palette and bottom bar are really small.
![Screenshot_20231228_140040](https://github.com/focus-editor/focus/assets/66821749/4562c2fe-d882-4aa4-8220-5be2e486d21c)

 - OS: Debian
- I'm on X11 with KDE Plasma as DE
 - Focus Version: [Version 0.2.0](https://github.com/focus-editor/focus/releases/tag/0.2.0)

**Comment by focus-editor** [comment]
Should be fixed in the main branch. If you download the latest nightly from here when it updates it should be fixed there https://ileonte.dev/focus-builds/Linux/nightly/

It updates every 4 hours.

Please reopen if the issue still persists.
