### ISSUE TITLE
There is no Quit or Exit in the command selector.

### ISSUE THREAD

**Issue by Gavin-Holt** [focus-editor/focus#260]
Hi,

There is no ```Quit```  or ```Exit``` in the command selector.

Isn't there another editor pilloried for [un-discoverable exit command](https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/)?

Kind Regards Gavin Holt

 - OS: Windows
 - Focus Version: 0.3.0

**Comment by focus-editor** [comment]
The problem with the editor you mentioned is that it runs in a console, while here you can exit by closing the window or using a standard OS close window shortcut, so not exactly a valid comparison here.

That said, we'll add it to the  command selector no problem

**Comment by Gavin-Holt** [comment]
Hi

Many thanks.

Kind Regards Gavin Holt

**Comment by Gavin-Holt** [comment]
Still no exit or quit command?

**Comment by focus-editor** [comment]
https://github.com/focus-editor/focus/commit/2cf649c2c0585bbdf3b4d1ac5c20d0b10e7cb2d1
