### ISSUE TITLE
Congratulations: Focus start-up is really fast.

### ISSUE THREAD

**Issue by Gavin-Holt** [focus-editor/focus#264]
Hi,

I use a little [utility](https://www.passmark.com/products/apptimer/index.php) to measure start-up time for applications. Focus is by far the fastest non-console editor. Please see the comparative start times for some other editors:

| Sorted by fastest to slowest |
| ------ |
| O:\MyProfile\editor\micro.exe - 5 executions |
| 0.0461 |
| 0.0459 |
| 0.0464 |
| 0.0460 |
| 0.0461 |
| O:\MyProfile\editor\confFocus\focus.exe - 5 executions |
| 0.0623 |
| 0.0775 |
| 0.0914 |
| 0.0788 |
| 0.0772 |
| O:\MyPrograms\EDITORS\confTSE\g32.exe - 5 executions |
| 0.0995 |
| 0.0774 |
| 0.0774 |
| 0.0774 |
| 0.0774 |
| O:\MyPrograms\EDITORS\Notepad2-MOD\Notepad2.exe - 5 executions |
| 0.0930 |
| 0.0930 |
| 0.0930 |
| 0.0931 |
| 0.0931 |
| O:\MyPrograms\EDITORS\confTSE\e32.exe - 5 executions |
| 0.1530 |
| 0.1620 |
| 0.1464 |
| 0.1525 |
| 0.1464 |
| O:\MyProfile\editor\ScITE.exe - 5 executions |
| 0.2648 |
| 0.2648 |
| 0.2336 |
| 0.2492 |
| 0.2492 |
| O:\MyProfile\editor\confNotepad++\notepad++.exe - 5 executions |
| 0.6398 |
| 0.6554 |
| 0.6555 |
| 0.6552 |
| 0.6398 |
| O:\MyPrograms\EDITORS\MPad\MPad64.exe - 5 executions |
| 1.1633 |
| 1.1990 |
| 1.1815 |
| 1.1631 |
| 1.1969 |
| O:\MyProfile\editor\confKate\bin\kate.exe - 5 executions |
| 18.2556 |
| 1.0999 |
| 1.1922 |
| 1.1139 |
| 1.0813 |

I don't think this is a cache effect as the first start (after reboot) is just as quick.

This is a major attraction, as I like to call my editor from my favorite [filemanager](https://textmode.netlify.app/) and it will be opened and closed repeatedly.

Kind Regards Gavin Holt

 - OS: Windows
 - Focus Version: 0.3.0

**Comment by focus-editor** [comment]
Thanks for the info. Perhaps it would be best shared on Discord or in the discussions rather than through an issue thought?

Do note that the Focus startup time depends on the size of the workspace because it loads all files from there when it starts.
