### ISSUE TITLE
Crash when logging in a thread

### ISSUE THREAD

**Issue by ostef** [focus-editor/focus#27]
Notice: I sent an email already about this to Jon, since it's a fix to be done in the Thread module, but I'm still making an issue to keep track of the bug and provide a quick fix.

The editor crashes when logging in a separate thread, when the logger is session_logger (really it crashes when a logger is set that does not expect context.logger_data to be null).

The fix for this would be to set each thread's starting_context.logger_data to context.logger_data, specifically:

In workspace.jai, line 43:
```
// @Temporary: fix for logger starting context logger data not being set correctly in thread_init
for * file_list_thread_group.worker_info
    it.thread.starting_context.logger_data = context.logger_data;
```

line 75:
```
// @Temporary: fix for logger starting context logger data not being set correctly in thread_init
for * scanner_thread_group.worker_info
    it.thread.starting_context.logger_data = context.logger_data;
```

**Comment by focus-editor** [comment]
Yes, that's why I removed all the logging from threads because I didn't have the time to investigate it properly

**Comment by focus-editor** [comment]
Thank you for providing a fix @ostef . Please reopen if you get a reply from Jon regarding this.
