### ISSUE TITLE
Crash with certain symbols when regex search is enabled

### ISSUE THREAD

**Issue by anssilap** [focus-editor/focus#272]
**Describe the bug**
If you type `^` or `$` symbol into "Find in buffer" field while regex search is enabled, program crashes with Fatal Error message popup:
```text
Assertion failed in file W:/focus/src/editors.jai at line 1023, char 9:
```

**To Reproduce**
1. Open any file
2. Go to "Find in buffer" (default Ctrl-F)
3. Enable regex search
4. Type in `^` or `$` symbol

**Expected behavior**
Handle the input without crash even if invalid

**Screenshots**
![image](https://github.com/focus-editor/focus/assets/6798318/3da858c7-8ff7-4ce1-98d9-486d2ad61bdc)

 - OS: Windows
 - Focus Version: 0.3.0

**Comment by focus-editor** [comment]
Thanks for the report, will fix asap

**Comment by focus-editor** [comment]
This issue should be fixed in the latest nightly, please download from here https://ileonte.dev/focus-builds/Windows/nightly/

**Comment by focus-editor** [comment]
I started rewriting regex search yesterday but didn't finish yet. When I'm
done this should be fixed as well

**Comment by focus-editor** [comment]
@anssilap the issue should be resolved now in the latest nightly. Please reopen if you find more regex-related bugs.
