### ISSUE TITLE
close_left_editor and close_other_editor not functioning properly

### ISSUE THREAD

**Issue by maxamundsen** [focus-editor/focus#274]
**Describe the bug**
Closing the 'other' editor from the right side editor does not work as intended.

**To Reproduce**
1. Open two editors on the left and right with different files
2. Put the right-side editor in focus
3. Execute either 'close_other_editor' or 'close_left_editor'

After executing the previous steps, the right-side editor closes instead of the left, however the right-side editor remains in focus.

**Expected behavior**
Closing the left-side editor or 'other' editor from the right should close the left editor and place focus to the left.

**Screen Capture**
![focus_iHV9B1MBp4](https://github.com/focus-editor/focus/assets/109674749/702967cd-8ff2-4c97-944a-dee86e129c64)

**Info**
 - OS: Windows 10
 - Focus Version: Release 0.3.0

**Comment by focus-editor** [comment]
Thanks for the report. People have complained about that, but we haven't been able to reproduce it ourselves yet - it's very weird. We'll look into it an see if we can find the reason

**Comment by focus-editor** [comment]
Ah OK it seems to only be the case when file open close animations are disabled - your screencast helped pinpoint the problem, thanks

**Comment by focus-editor** [comment]
When a new nightly is built (they build every 4 hours) the fixed version will be available from here. https://ileonte.dev/focus-builds/Windows/nightly/

Please let us know if you see any other issues
