### ISSUE TITLE
'minimum_os_version' is not a member of Build_Options

### ISSUE THREAD

**Issue by peter-slattery** [focus-editor/focus#283]
**Describe the bug**
When compiling with jai beta 0.1.081, the compiler reports `/Users/ps/work/focus/first.jai:15,13: Error: 'minimum_os_version' is not a member of Build_Options.`

**To Reproduce**
1. Clone main
2. Run `jai first.jai - release`
3. Note the error that the compiler reports

**Expected behavior**
The application should compile successfully.

**Additional context**
I don't see anything in the jai beta CHANGELOG.txt that indicates a change to the identifier. 
The solution is to just change `minimum_os_version` to `minimum_macos_version`, which does exist.

**Comment by ileonte** [comment]
Since the merge of https://github.com/focus-editor/focus/pull/258 the minimum compiler version required to compile Focus is `0.1.083`.

**Comment by peter-slattery** [comment]
Oops, that'll do it. I updated the compiler on my windows but not on my mac. Sorry / thanks for the quick reply.
