### ISSUE TITLE
Close current editor misbehaving when disable_file_open_close_animations is true

### ISSUE THREAD

**Issue by maxamundsen** [focus-editor/focus#284]
This bug is very similar to #274 

**To Reproduce**

- Set `disable_file_open_close_animations:     true` in the global config
- Open 2 side-by-side editors
- Switch to right editor
- Close the current window (Ctrl-W by default)

The right editor will close, however it still remains in focus instead of focusing the left editor.

 - OS: Windows 10
 - Focus Version: focus-nightly-6750272

**Comment by focus-editor** [comment]
On no this is terrible, thanks for reporting, will fix asap
