### ISSUE TITLE
keymap combinations assume QWERTY (macOS)

### ISSUE THREAD

**Issue by thisma** [focus-editor/focus#29]
- OS: macOS 12
 - Focus Version: 0.1.6

**Describe the bug**
On macOS the keymap combinations assume US QWERTY is the keyboard layout.

*Example 1*
**To Reproduce with AZERTY layout**
1. Go to 'System Preferences -> Keyboard -> Input Sources'
2. Click on '+'
3. In the search field type 'French'
4. Click ABC - AZERTY
5. Click Add
6. Click ABC - AZERTY
7. Open Focus
8. Press Command-N (note the 'N' key is in the same place on both the AZERTY and QWERTY layouts)
9. Type "testing"
10. Press Command-Z (note the 'Z' key on the AZERTY layout is in the location of the 'W' key on the QWERTY layout, and vice-versa)

**Expected behavior**
The typing of the word 'testing' to be undone.

**Actuall behaviour**
The file is closed

*Example 2*
**To Reproduce with Dvorak layout**
1. With a US keyboard layout
2. Open Focus
3. Press Command-Shift-P
4. Type 'Open Global Config'
5. Press 'Return'
6. Move the cursor to the beginning of the 'allow file extensions' list (which begins with ".jai .c .cpp"
7. Type ".plist "
8. Go to 'System Preferences -> Keyboard -> Input Sources'
9. Click on '+'
10. In the search field type 'dvorak'
11. Click Dvorak
12. Click Add
13. Click Dvorak
14. Go back to Focus
15. Press Command-Z (note the 'Z' key on the Dvorak layout is in the location of the '/' key looking at a QWERTY layout)

**Expected behavior**
The typing of the word ".plist " to be undone.

**Actuall behaviour**
The 'Toggle Code Comment' command is issued, adding a "# " to the beginning of the line.

**Comment by focus-editor** [comment]
This is a known issue with the Input jai module working differently on different OS's - it will be definitely fixed, just not sure what the best way to do it is. 
Please note that the macOS version is expectedly buggy

**Comment by thisma** [comment]
> Please note that the macOS version is expectedly buggy

I figured that would be the case. I have figured there would be much less attention given to macOS from most Jai projects at this point.

I’ve found other issues too. If there’s no one available to work much on macOS right now perhaps I should wait to report them? I wish I was in the Jai beta and could help more than just finding issues. I’m pretty hopeful about Jai and Focus.

**Comment by focus-editor** [comment]
Please do report those issues, it's good for tracking. I'm just trying to
set expectations.

We don't have any invites into the beta to give away unfortunately, so you
have to try to get in yourself if you want.

**Comment by ileonte** [comment]
@thisma I believe this should work as expected now, please try this build of the editor: https://ileonte.dev/focus-builds/macOS/dev/Focus-0.3.1-5135070-Intel.dmg
Note: key composition is not supported but basic keyboard layout should be respected now.

**Comment by ileonte** [comment]
Closing this for now, we can reopen if needed.
