### ISSUE TITLE
Focus does not compile with the latest jai beta: 0.1.084

### ISSUE THREAD

**Issue by Roman-Skabin** [focus-editor/focus#291]
**Describe the bug**
Focus does not compile with the latest jai beta: 0.1.084

**To Reproduce**
1. Download the latest jai beta (0.1.084)
2. `jai -x64 first.jai` or `jai first.jai`

**Expected behavior**
Focus compiles with the latest jai beta

**Screenshots**
![image](https://github.com/focus-editor/focus/assets/40520199/17e8691b-b9bf-4ee0-840a-d64dfde08781)

- OS: Windows 11
- Focus Version: 6c1ebae404b34e0b88c4cd3b40a9189276bc704f

**Comment by ileonte** [comment]
Preliminary patch to fix the Windows build:

```
diff --git a/modules/Runtime_Support.jai b/modules/Runtime_Support.jai
index 0d58834..faaf3d1 100644
--- a/modules/Runtime_Support.jai
+++ b/modules/Runtime_Support.jai
@@ -1,5 +1,7 @@
 #module_parameters(ENABLE_BACKTRACE_ON_CRASH: bool);
 
+OS_IS_UNIX :: OS == .MACOS || OS == .LINUX || OS == .PS5 || OS == .IOS || OS == .ANDROID;
+
 debug_break :: () #no_context {
     if #compile_time {
         compile_time_debug_break :: () #compiler #no_context;
diff --git a/src/platform/windows.jai b/src/platform/windows.jai
index 886c1dc..9f9b29d 100644
--- a/src/platform/windows.jai
+++ b/src/platform/windows.jai
@@ -299,6 +299,7 @@ REFRESH_TIMER_ID :: 0;
 
 WM_USER :: 0x0400;
 
+_ :: #library,system,link_always "advapi32";
 user32   :: #system_library "user32";
 kernel32 :: #system_library "kernel32";
 shell32  :: #system_library "shell32";
```
(also attached just in case copy-paste is being weird: [win.patch](https://github.com/focus-editor/focus/files/14078899/win.patch))

I haven't checked the other platforms yet.

**Comment by Roman-Skabin** [comment]
MacOS build works with just `OS_IS_UNIX :: OS == .MACOS || OS == .LINUX || OS == .PS5 || OS == .IOS || OS == .ANDROID;`, but only for x64. Arm64 build is not compiled because of atomics (they are implemented only for x64, `atomic_swap` particularly).

**Comment by ileonte** [comment]
Linux also builds by just adding `OS_IS_UNIX` to our copy of `Runtime_Support` so I pushed that change so people can at least build on Linux and macOS.
For Windows I'm not sure how I feel about pushing the `Advapi32` linking fix, I would honestly rather wait for the next compiler beta since that allegedly fixes that problem.
