### ISSUE TITLE
Feature: Ability to reload file from disk when [modified on disk] is shown

### ISSUE THREAD

**Issue by IRooc** [focus-editor/focus#293]
**Describe the bug**
When you open a file in focus and start editing without hitting save and edit the file in another way you get the helpful message [modified on disk]. It would then be good to be able to have the option to reload the file from disk and thus discarding the focus changes,  instead of just saving over the file with the focus changes.

**To Reproduce**
1. Open file in focus
2. Edit the file slightly
3. Open the same file from disk in another editor
4. Modify the file and save
5. See the [modified on disk] message in focus

**Screenshots**
![image](https://github.com/focus-editor/focus/assets/5981147/8c7cae45-9db5-4ef3-a3c5-a8706a5d947e)

 - OS: Windows
 - Focus Version: 0.3.1

**Additional context**
It would also be nice to see the "changed" status in the navigate_to_file option 
the open_file_by_name option shows this:
![image](https://github.com/focus-editor/focus/assets/5981147/1d368b7c-38e1-4e92-af78-c4b0a6c76455)
the navigate_to_file shows this:
![image](https://github.com/focus-editor/focus/assets/5981147/885ccdae-36e0-498f-a775-eaaca8d8cbe5)

**Comment by IRooc** [comment]
One extra sidenote. If you switch branches in git and a file disappears, it is correctly marked "deleted on disk". But if you go back to the branch that had the file it remains marked as deleted, even though the file exists again.

Workaround for this is of course to save it, but the file also doesn't show up in Ctrl+Tab and Ctrl+P and O dialogs anymore until you re-save it.

Workaround for the modified on disk issue for now is to reload the project (which triggers the save dialog where you can discard the changes)

**Comment by focus-editor** [comment]
All these changes are now in the main branch.

Please check them in the next nightly and close the ticket unless there are issues.

**Comment by IRooc** [comment]
Thanks, works great!
