### ISSUE TITLE
Bug: Enter removes character at cursor

### ISSUE THREAD

**Issue by lannior** [focus-editor/focus#295]
**Describe the bug**
Sometimes pressing Enter will delete the character under the cursor.

**To Reproduce**
Couldn't reproduce it, but it occured multiple times in the wild.

**Expected behavior**
I expect it to not delete the character.

**Screenshots**

**Additional context**
[Clip of this bug happening on my stream](https://www.twitch.tv/videos/2048901743)
(Happened once before, but only the last one is shown in the clip)

**Comment by focus-editor** [comment]
Thanks for providing a video. If you look closely you'll notice that the curly brace the cursor was on was selected, so pressing Enter removed it.

**Comment by Weldify** [comment]
I see, that makes sense 🤣. Although it was very hard to see that the cursor selected something in this case, maybe cursor selections could be more clear...

It would helpful if, for example, you could change the shape of a regular cursor vs a selection cursor.

**Comment by focus-editor** [comment]
If that's a problem for you perhaps a line-cursor would work better (`cursor_as_block: false` in the config)?
