### ISSUE TITLE
Can't open jai files with focus on MacOS

### ISSUE THREAD

**Issue by Roman-Skabin** [focus-editor/focus#297]
**Describe the bug**
MacOS says you can't open .jai files with Focus

**To Reproduce**
open -a Focus first.jai

**Expected behavior**
The file is open in Focus

**Screenshots**
<img width="271" alt="Screenshot 2024-01-31 at 12 20 48" src="https://github.com/focus-editor/focus/assets/40520199/b2013a3f-2729-48c4-8875-2ac3f218774a">

- OS: MacOS Sonoma 14.2.1
- Focus Version: 51350709194e0da6e7e723ff6c0f4850cc4948a7

**Comment by ileonte** [comment]
Please try with this build: https://ileonte.dev/focus-builds/macOS/dev/Focus-0.3.1-72c5015-Intel.dmg
You should get `Focus` as an option under `Open With` in the right-click menu in Finder (for text files, I will look into maybe adding this option for directories as well). It should also be possible to open files via `open -a Focus` from the terminal.

**Comment by Roman-Skabin** [comment]
1. I will try this build tomorrow, I don’t have access to mac right now
2. `open -a Focus first.jai` is the exact way I tried. If I open Focus first and then cmd-O the file everything’s fine, but if I open a file with Focus from terminal I have that window.

**Comment by Roman-Skabin** [comment]
@ileonte Since 72c50155a624e1a9c29467b6fe0b160034d60f7c it works now
1. I can open a file with  `open -a Focus first.jai` and even with just `open first.jai`
2. Also I have `Focus (default)` in `Open With` menu

**Comment by ileonte** [comment]
Thank you for testing!
