### ISSUE TITLE
Feature Request: Option to clear build output

### ISSUE THREAD

**Issue by CELLTH** [focus-editor/focus#298]
I find the build window to be very useful as a buffer to sift through compiler errors and warnings. In cases that I rename variables and or move them across structs, I ideally want to search in the output window to make sure I have found every instance of warnings and errors. Being able to only see the compiler output from the last build would help me quickly guarantee that I got every instance and instances from previous builds will not show up in the search.

**Comment by focus-editor** [comment]
This should be available in the next nightly. Just specify `clear_build_output_before_running: true` for one command or globally. Please reopen if there are issues

**Comment by CELLTH** [comment]
The functionality itself is great! But it crashes exactly on the 3rd build with this new option enabled.

**Comment by focus-editor** [comment]
Doesn't crash for me - do you have a crash report?

**Comment by CELLTH** [comment]
Here are the log files: 
<details><summary>log.txt</summary>
<p>

2 February 2024, 14:48:25: Started watching external directory 'C:/bin/focus/projects'
2 February 2024, 14:49:11: Executing build command [Build]
2 February 2024, 14:49:11: '' added     work '' to the available list at time 50.186869.
2 February 2024, 14:49:11: '' assigned  work ''   to thread 13 at time 50.186949.
2 February 2024, 14:49:11: Executing build command [Build]
2 February 2024, 14:49:12: '' completed work '' from thread 13 at time 51.288265 (elapsed: 1.101396).
2 February 2024, 14:49:12: '' is returning 1 result from get_completed_work().
2 February 2024, 14:49:12: Build command [Build] finished
2 February 2024, 14:49:12: Executing build command [Build]
2 February 2024, 14:49:12: '' added     work '' to the available list at time 51.651063.
2 February 2024, 14:49:12: '' assigned  work ''   to thread 13 at time 51.651079.
2 February 2024, 14:49:12: Executing build command [Build]
2 February 2024, 14:49:13: '' completed work '' from thread 13 at time 52.679605 (elapsed: 1.028542).
2 February 2024, 14:49:13: '' is returning 1 result from get_completed_work().
2 February 2024, 14:49:13: Build command [Build] finished
2 February 2024, 14:49:13: Executing build command [Build]
2 February 2024, 14:49:13: '' added     work '' to the available list at time 52.90921.
2 February 2024, 14:49:13: '' assigned  work ''   to thread 13 at time 52.909219.
2 February 2024, 14:49:13: Executing build command []
2 February 2024, 14:49:14: '' completed work '' from thread 13 at time 53.827381 (elapsed: 0.918171).
2 February 2024, 14:49:14: '' is returning 1 result from get_completed_work().


</p>
</details> 

<details><summary>log_error.txt</summary>
<p>

2 February 2024, 14:49:11: While running the command: 'build.bat', we were unable to create the process. Error code: 2, description: The system cannot find the file specified.
2 February 2024, 14:49:12: While running the command: 'build.bat', we were unable to create the process. Error code: 2, description: The system cannot find the file specified.
2 February 2024, 14:49:13: While running the command: 'build.bat', we were unable to create the process. Error code: 2, description: The system cannot find the file specified.


</p>
</details>

**Comment by focus-editor** [comment]
Do you see a focus-crash-report.txt next to the exe somewhere?

**Comment by CELLTH** [comment]
No it’s not there

**Comment by focus-editor** [comment]
@CELLTH please can you try a debug build and see if you could get a traceback there when it crashes - https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv

Also if it doesn't produce a traceback would you be able to run it in a debugger and see where it crashes? Thanks

**Comment by CELLTH** [comment]
No trace back is produced. This is as far as I can go with the debugger. Here is where it crashes in the debugger:

![image](https://github.com/focus-editor/focus/assets/126894359/40289eb8-dcce-48b7-ac62-33e967c4e790)

Values for running_command:
![image](https://github.com/focus-editor/focus/assets/126894359/80aebe55-b9b0-4c83-a811-7120f5176fb2)

**Comment by focus-editor** [comment]
Looks like a memory corruption bug. Thanks - we will investigate

**Comment by focus-editor** [comment]
@CELLTH please try this build https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv - is the problem still there?

**Comment by CELLTH** [comment]
yeah now it's not working at all. It freezes on the first build attempt and I can't even pause the execution or the kill the app from the debugger. If it would help, I can hop on a discord call to try out a few builds or configs.

**Comment by focus-editor** [comment]
Do you have a big workspace? Are you trying to run a build before the workspace has finished scanning by any chance? Just trying to rule out a possible race condition. So now it freezes every time you run a build command? Please can you show your build config?

**Comment by CELLTH** [comment]
No my workplace is relatively small sized and it is scanned instantly. I'm running the build command several seconds after opening the workspace. 

I'm using the ninja build system and upon further tests, it works well under the condition that ninja doesn't have any new files to build. But when I attempt to rebuild everything, it hard freezes every single time. Since rebuilding outputs many more lines, I assume it has something to do with that.

Here is my build config: 
![image](https://github.com/focus-editor/focus/assets/126894359/b7f0b116-0e21-47f2-8e21-80f2ddfc2988)

**Comment by focus-editor** [comment]
@CELLTH please try another build https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv

**Comment by focus-editor** [comment]
Does ninja write new files when doing a full rebuild? If the last build I sent doesn't work we'll have to hold off a bit and then add more logging, disable the file watcher and try again. Remote debugging is a pain :)

**Comment by CELLTH** [comment]
The issue persists. Ninja does write new files but none of those files are in the current workspace. The build directory is totally separate from the source files directory. 
> Remote debugging is a pain :)

Yeah I understand, let me know what I can do to help :)

**Comment by focus-editor** [comment]
I have been running the editor with this option on for a week and haven't encountered any issue. I would appreciate if you could give me a repro project or something that I could run on my machine, which consistently crashes on yours.

**Comment by focus-editor** [comment]
@CELLTH please create a new bug when you have a repro we could use to track down the bug. Thanks.
