### ISSUE TITLE
Bug: wrong behavior for key combinations ending with arrow keys

### ISSUE THREAD

**Issue by JBJones2020** [focus-editor/focus#300]
**Describe the bug**
If I bind scroll_viewport_down to Alt-B ArrowDown, and then hit Alt-B, ArrowDown, it will continue to scroll down till the end of the file even if the ArrowDown key has long since been released.

**To Reproduce**
1. Find an unbound key, e.g. Alt-B.  Bind Alt-B Arrowdown to scroll_viewport_down in the global.focus-config.
2. Open a long file and press Alt-B Arrowdown.  Don't hold Arrowdown.

**Expected behavior**
I expect the viewport to scroll down by several lines or maybe a page.  On my system, it scrolled all the way down to end of file.

**Screenshots**
n/a

 - OS: KDE Plasma on Manjaro
- If on Linux - please specify whether you're on Wayland or X11
              Linux_Display information:
                desired backend    : PREFER_BEST_USER_EXPERIENCE
                active backend     : WAYLAND
                desired GL backend : AUTOSELECT
                active GL backend  : EGL
            Wayland_Display.{
                base = {
                    type = Wayland_Display; 
                    app_id = "dev.focus-editor.focus"; 
 - Focus Version: 0.3.1

**Additional context**
n/a

**Comment by JBJones2020** [comment]
for move_selected_lines_down, mapping it to a two char sequence ending in ArrowDown works just fine on my machine.  This includes holding ArrowDown and then releasing it.

**Comment by focus-editor** [comment]
That action is not a hold action. The scroll actions are.

**Comment by focus-editor** [comment]
@JBJones2020 please try again when the next nightly is built. It should be fixed now hopefully.
