### ISSUE TITLE
Bug: build/run commands fail to redirect output

### ISSUE THREAD

**Issue by csimo29** [focus-editor/focus#301]
running on windows 11, v0.3.0

-- attempted usage --

[build, run, redirect output]  
build_command:          g++ -o out example.cpp
run_command:            out.exe > output.txt
key_binding:            F5

Build command is successful
run command runs in build window using out.exe 
output.txt was not created or overwritten

**Comment by ileonte** [comment]
Redirecting output via `>` is a shell construct. If you want that to happen you should use something like `cmd /c 'out.exe > output.txt'` as your run command.
