### ISSUE TITLE
Bug: C++ Syntax Highlighting Glitch

### ISSUE THREAD

**Issue by AhmedLilah** [focus-editor/focus#303]
I noticed a bug in C++ syntax highlighting  where it recognizes some of the standard containers (vector, array, map, set, queue, deque) as a type or a keyword in the include statement

**To Reproduce**
1. Open a C++ file and write "#include <vector>

**Expected behavior**
the word "vector" will be highlighted as a type or a reserved keyword.

**Screenshots**
![image](https://github.com/focus-editor/focus/assets/67424460/7a8488eb-2c30-4afd-9742-d6739fb528ff)

 - OS: Windows
 - Focus Version: 0.3.1

**Comment by focus-editor** [comment]
FYI this is not a glitch, C++ highlighting is just not implemented (it's being highlighted as C + there are a few C++ keywords). We accept contributions for highlighting.

**Comment by AhmedLilah** [comment]
I would very much be happy to contribute to the project.
I don't know if this would be possible however without having access to a Jai compiler. 
However, if there are other ways I would like to help.

**Comment by focus-editor** [comment]
This particular issue should be fixed in the most recent release.

There's no proper C++ highlighting still.
