### ISSUE TITLE
Feature: Vim Motion/Modes

### ISSUE THREAD

**Issue by AhmedLilah** [focus-editor/focus#305]
**Feature**
Hi, 
Thanks for this amazing editor. 
I'm currently impressed by how easy and configurable it is but for those of us who haven't had the privilege to be a part of the Jai beta tester program.
I would like to have the same editor with only one more Feature.
That is Vim-Like Modes/Motion.

**Comment by focus-editor** [comment]
Sorry there will probably never be a vim-mode in the main editor fork. Someone might fork the editor and add it at some point but this is inherently a non-modal editor and it's intended to stay this way.
