### ISSUE TITLE
Bug: Settings in Linux version

### ISSUE THREAD

**Issue by HSGWHRSI** [focus-editor/focus#309]
The Linux version of the editor does not generate the default files and folders when running. I tried copying them over from Windows but they are not recognized by the editor. No themes, no projects, no global configurations, nothing. It will open with the default settings, font size and all, every time.

**Comment by ileonte** [comment]
On Linux the location of the configuration files is `${HOME}/.config/focus-editor/`. You should find the default config file and the projects directory there.

**Comment by HSGWHRSI** [comment]
Ok, thank you.
