### ISSUE TITLE
Feature Request: Smart line wrapping

### ISSUE THREAD

**Issue by HSGWHRSI** [focus-editor/focus#310]
Could you mimic 4coder's style of line wrapping where it nicely aligns the code and adds an indicator to the right? SDL_CreateWindow and SDL_CreateRenderer in the example below are each written on one line.

![Capture](https://github.com/focus-editor/focus/assets/160215314/378767a1-a497-464c-95e5-e9fcbe4756cd)

**Comment by focus-editor** [comment]
While some people would certainly prefer that, others find it annoying, so it would better align with the editor's philosophy to keep the line wrapping simple.
