### ISSUE TITLE
Syntax highlighting for C

### ISSUE THREAD

**Issue by HSGWHRSI** [focus-editor/focus#314]
The editor does not recognize clock_t and time_t likes it does uint8_t and so on. Would love them added.

**Comment by ileonte** [comment]
Starting with [commit a5c12d2](https://github.com/focus-editor/focus/commit/a5c12d217c1c68b88bc4b849409d6f5cf0c93aef) `clock_t` and `time_t` should be highlighted. For Windows and Linux this change will automatically be included in the next nightly builds (https://ileonte.dev/focus-builds/). If you need a macOS release please let me know, I have to build that manually for now.

**Comment by HSGWHRSI** [comment]
Great!
