### ISSUE TITLE
Feature Request: Use the current file in the build step

### ISSUE THREAD

**Issue by IRooc** [focus-editor/focus#325]
**Describe the feature**
It would be a nice feature if the currently active filename could be used in the buildstep. 1 example would be to have an external linter/prettier run through the file.

**To Reproduce**
Example would be:
-  quick-lint-js.exe %FILE%

or some other tool you'd like to run on the current file 

**Additional context**
Maybe you have a library of scripts that you would like to run individually

**Comment by dcourtois** [comment]
Yes!! I would even go slightly further and add a few more "variables" that could be substituted. From the top of my mind being able to have those available to commands would be really helpfull for more generic build commands:
- full name of the current file (so we can have a "build and run current file" build command, very convenient for quick tests)
- folder of the current file (if the command needs to output stuff next to the "built" file)
- name of the file, and maybe name of the file without extension (to name the executable after the file)
- working directory of the command

**Comment by focus-editor** [comment]
This will be available in the next nightly and will be released in 0.3.4 soon. Please reopen if you notice issues.

**Comment by IRooc** [comment]
Just leaving this here so people know how to use it, thanks! This code shows the tokens that are used in parsing the command
https://github.com/focus-editor/focus/blob/8071628b0ef763fa9a7bf3283555466e01c9a8d4/src/build_system.jai#L516

**Comment by focus-editor** [comment]
This is not the full list. There's also BUILD_WORKING_DIR and RUN_WORKING_DIR. 
The full list is in the release changelog and in the default config examples

**Comment by IRooc** [comment]
The example project file part:
https://github.com/focus-editor/focus/blob/424c17de58dd7698ae83b73467d87e503d9d8441/config/example-project.focus-config#L54-L61
