### ISSUE TITLE
Plans for plugin support?

### ISSUE THREAD

**Issue by mathaou** [focus-editor/focus#33]
Most likely answer is "no, just fork and modify source", but if I think of other editors like helix or neovim, it would be handy to have some kind of LSP support to help catch compilation issues (this can be an opt-in type of experience). I don't need an IDE-like experience. I find that go to symbol / find usages, split view, and easy file system traversal are about all I need to stay sane while working in a codebase, but I'm doing embedded work right now and the cross compilation toolchain takes forever - so being able to see comp errors as I'm developing would also be helpful.

**Comment by mathaou** [comment]
See also GDB integration so I didn't have to have a separate debugger program.

**Comment by focus-editor** [comment]
Keeping the number of features down is one of the goals of this editor. Whether or not plugin support will be added remains to be seen, but right now this feature is definitely not planned. 

Open source code enables infinite customization, so things implemented by others can be considered to be added to the main editor, but only if they fit nicely and don't add too much complexity overall. I doubt we'll ever add a debugger, but don't know 100%

**Comment by mathaou** [comment]
If I was in beta I'd take a crack at it but alas

**Comment by SamHSmith** [comment]
I would like to add this comment. All the other editors that I have used suck compared to focus. And they all have plugins in some form. It could be an accident or "plugin culture" causes horrible software.

**Comment by mathaou** [comment]
> LSP support is not out of the question, but if we provide it it won't be through a plugin, it will most likely be built in and maybe even you'll have to enable it at compile time, but we'll see

I like the compile time feature idea, but that means that those building from source will need to be in beta. Or maybe Jai will be public by then. I've seen FOSS repos with separate binaries per platform broken down by feature, so there's definitely a history of that distribution model.

**Comment by BrandonCisneros** [comment]
Hello from the future! Love the idea as well @mathaou ...but alas, the Jai compiler is still not released for public consumption yet.
