### ISSUE TITLE
Update Objective_C module to jai 0.1.089

### ISSUE THREAD

**Issue by Roman-Skabin** [focus-editor/focus#331]
There is currently no way to build focus for MacOS, for ARM64 particularly. It seems like new Objective_C module will allow it: there are a lot of new ARM64 bindings and other stuff.

--
OS: MacOS Sonoma 14.4.1
CPU: M1 (arm64)
commit: 0820dd2678bc62f35344e7d09d2802a6f9e243d9

**Comment by focus-editor** [comment]
I don't have the hardware to test it. Would be nice if someone else did it

**Comment by Roman-Skabin** [comment]
I've tried, but I haven't win this. To many x64 specific asm blocks. Have to wait for the full Arm support in Jai modules.

**Comment by ileonte** [comment]
I've updated our copy of `Objective_C` to the one from Jai `0.1.089`.
Note that this doesn't mean that building the editor for `arm64` works now, there's a bunch of other stuff that's still not ready for that.
