### ISSUE TITLE
Resizing the focus window in Wayland crashes the window manager

### ISSUE THREAD

**Issue by aolo2** [focus-editor/focus#332]
**Describe the bug**
Swithcing the focus window to "floating" mode in sway and then resizing it triggers an assert in sway and crashes it.

**To Reproduce**
1. Start a sway session
2. Open focus
3. Switch it to floating mode
4. Resize it (I'm using Alt+Right Mouse Button)
5. Observe

**Expected behavior**
The window should resize normally

**Screenshots**
I recorded a video with my phone, because I obviously can't screen record since the WM crashes. Sorry for the janky video, I needed both hands to resize the window

https://github.com/focus-editor/focus/assets/17429989/431b72ed-f584-472e-91d3-13c6c49ad1b7

- OS: Linux (debian sid)
- Wayland
- Focus Version: 0.3.2

**Details**
Here's what sway logs say:
```
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
2024-04-05 12:49:24 - [main.c:293] Found config * for output DP-1 (Acer Technologies VG270U P 0x1071B01B)
[
  {
    "success": true
  }
]
xkbcommon: loaded libxkbcommon.so.0
WAYLAND: loaded libwayland-client.so.0
WAYLAND: loaded libwayland-egl.so.1
WAYLAND: loaded libwayland-cursor.so.0
Started watching external directory '/home/aolo2/.config/focus-editor'
EGL: loaded libEGL.so.1
sway: render/pass.c:33: wlr_render_pass_add_texture: Assertion `box->x >= 0 && box->y >= 0 && box->x + box->width <= options->texture->width && box->y + box->height <= options->texture->height' failed.
```

**Comment by aolo2** [comment]
As far as I can tell, the same issue persists for focus 0.3.3:
```
aolo2@avx:~$ cat sway.log 
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
2024-04-06 12:24:19 - [main.c:293] Found config * for output DP-1 (Acer Technologies VG270U P 0x1071B01B)
sway: render/pass.c:33: wlr_render_pass_add_texture: Assertion `box->x >= 0 && box->y >= 0 && box->x + box->width <= options->texture->width && box->y + box->height <= options->texture->height' failed.
 err: wayland.c:1405: failed to read events from the Wayland socket: Broken pipe
 err: wayland.c:1977: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:1977: failed to roundtrip Wayland display: Broken pipe
 err: wayland.c:1977: failed to roundtrip Wayland display: Broken pipe
warn: terminal.c:1802: slave exited with signal 1 (Hangup)
 err: wayland.c:1942: failed to flush wayland socket: Broken pipe
 ```

**Comment by ileonte** [comment]
Somebody on the Discord ran into the same issue on Sway. As soon as I have some time I will try to investigate.

**Comment by ileonte** [comment]
This should be fixed now.
@aolo2 please test with the latest nightly build: https://ileonte.dev/focus-builds/Linux/nightly/focus-linux-nightly-283491e

**Comment by aolo2** [comment]
The latest nightly works beautifully for me!

**Comment by ileonte** [comment]
Thank you for testing!
