### ISSUE TITLE
Assertion failed in file W:focus/src/buffer.jai at line 180, char 5: buffer is dirty, can't calculate line of offset

### ISSUE THREAD

**Issue by JesseRMeyer** [focus-editor/focus#336]
Hi, on the latest 0.3.4-2, running the build command crashes focus with the message in the title.  This did not occur on the dropbox version you provided from Discussions the other day.

**Comment by focus-editor** [comment]
Does this always happen? Can you give more details please?

**Comment by JesseRMeyer** [comment]
Sorry for the rush.  No it doesn't occur everytime.  Seems to only happen when there is a regex match for an error when a build fails.  In _that_ case, it is failing every time for me.

**Comment by focus-editor** [comment]
Please disable the error regex and send here the build output that would
crash the editor, together with the regex.
I won't be able to look at it right away but will do first thing when I can

**Comment by JesseRMeyer** [comment]
```
F:/Play/server/src/main_windows.odin(18:3) Syntax Error: #partial can only be applied to a switch statement
	#partial switch err := win32.System_Error(win32.WSAGetLastError( ...
	^
F:/Play/server/src/main_windows.odin(18:12) Syntax Error: You cannot use a switch statement in the file scope
	... partial switch err := win32.System_Error(win32.WSAGetLastError() ...
	            ^
F:/Play/server/src/main_windows.odin(18:12) Syntax Error: You cannot use a switch statement in the file scope
	... partial switch err := win32.System_Error(win32.WSAGetLastError() ...
	            ^
ERROR: exit code 1  [Elapsed: 0.037s]
```

> ^(?P<file>.*)[(](?P<line>\d+)[:](?P<col>\d+)[)] (?P<type>Syntax Error|Syntax Warning|Error|Warning): (?P<msg>.*)

**Comment by focus-editor** [comment]
Thanks. Other people have reported crashes which indicate there's a memory
allocator issue. Please revert to the previous version until it's fixed

**Comment by focus-editor** [comment]
Unfortunately I can't reproduce it no matter how hard I'm trying, which is bad. I might have to send you a couple more builds to test later.

**Comment by focus-editor** [comment]
@JesseRMeyer please can you try a debug build here and tell me if you're seeing the error there https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv?usp=sharing

**Comment by JesseRMeyer** [comment]
Sure, and yes, I still am.

Also I note a crash-report.txt in the focus directory which is a stack dump which may help.

```
Assertion failed in file W:/focus/src/buffer.jai at line 180, char 5: 
buffer is dirty, can't calculate line from offset

Stack trace:
W:/focus/modules/Runtime_Support.jai:816: report_error_in_yer_face
W:/focus/modules/Runtime_Support.jai:791: report_failed_assertion_more_visibly
W:/focus/modules/Runtime_Support.jai:108: runtime_support_assertion_failed
C:/jai/modules/Basic/module.jai:87: assert_helper
W:/focus/src/buffer.jai:180: offset_to_real_line
W:/focus/src/editors.jai:1217: select_line
W:/focus/src/build_system.jai:729: go_to_current_build_error
W:/focus/src/build_system.jai:367: go_to_next_build_error
W:/focus/src/build_system.jai:232: build_system_update
W:/focus/src/main.jai:309: main
```

**Comment by focus-editor** [comment]
Thanks, that's helpful. I think this one fixes it https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv

**Comment by JesseRMeyer** [comment]
That seemed to fix it! I toyed around a bit and could not recreate the crash anymore.
