### ISSUE TITLE
Couldn't open any config file from command

### ISSUE THREAD

**Issue by jejikeh** [focus-editor/focus#337]
Focus is unable to open project config files and global config from the command. The drag-and-drop feature works fine if launched without switching to a project. Otherwise, Focus crashes.

![image](https://github.com/focus-editor/focus/assets/44530103/880f9ba5-05f2-4971-be4b-2685f8797129)

 - OS: MacOS
 - Focus Version: 0.3.4-2

**Comment by focus-editor** [comment]
@jejikeh please try this build and tell me if you notice any issues there https://drive.google.com/file/d/14adIvQxL5u-MWJWJ9faNOMfB7SzgIgwH/view?usp=drive_link

**Comment by jejikeh** [comment]
@focus-editor I tested, and it seems that this issue has been resolved! Thank you very much!
