### ISSUE TITLE
Build error_regex doesn't highlight last error/warning

### ISSUE THREAD

**Issue by IRooc** [focus-editor/focus#338]
**Describe the bug**
I run the quick-lint-js exe which is downloadable here https://quick-lint-js.com/install/cli/ on the %FILE% using the  following build command:

```
[Lint]   # <- command name. Can be arbitrary
clear_build_output_before_running: true
build_command:          c:/Rc/Tools/quick-lint-js/bin/quick-lint-js.exe %FILE%
key_binding:            F6
error_regex:            ^(?P<file>.*):(?P<line>\d+):(?P<col>\d+): (?P<type>error|warning): (?P<msg>.*)$
```

The build output highlights all but the last warning/error in the output:
![image](https://github.com/focus-editor/focus/assets/5981147/67a5a682-31a2-40c3-86ac-afb8525308d5)

**To Reproduce**
1. download the linter
2. add the Lint step as shown above (modify path)
3. run the linter on the project file itself (I know not a js file but that doesn't matter for the repro case)

**Expected behavior**
Able to jump to the last error with F8 default binding

 - OS: Windows Version 0.3.4-1

**Additional context**
I tried it also in actual JS file but the last entry is still not enabled

**Comment by focus-editor** [comment]
This should've been fixed in 0.3.4-2, but we had to roll it back temporarily. Please check this build, it should be fixed there https://drive.google.com/drive/folders/16akMNqEJmfuY2FX6KrbmFLhieMdxzetv
