### ISSUE TITLE
macOS: Extra cursors appear when regaining focus

### ISSUE THREAD

**Issue by Khrob** [focus-editor/focus#35]
Whenever I click back into the focus window, a new cursor appears. Defocusing and refocusing adds more and more until you press escape.

I built from commit 50cbc6f. 

Will try and have a look tonight.

**Comment by focus-editor** [comment]
It must be because it misses the key up event for CMD and keeps thinking it's pressed

**Comment by cookednick** [comment]
Yeah I saw this too. It's now in the macOS todo. Might be something we'd need to fix in the Input module. We could probably for now just act as though all keys are up whenever our window regains focus.

**Comment by Khrob** [comment]
Works like a charm in 0.1.7

**Comment by Khrob** [comment]
I tell a lie... it works when changing focus with the mouse, but if I navigate away with command+tab and come back with the mouse, it's still there.

**Comment by focus-editor** [comment]
Yeah I don't think we've addressed this yet

**Comment by cookednick** [comment]
I addressed this in [the most recent commit](https://github.com/focus-editor/focus/commit/da5dd3dc14df148989b878cf51fb401b81714bd7). So in the next release, this should no longer happen. 👍

(It was getting on my nerves.)
