### ISSUE TITLE
Feature request: Relative paths in directory local project configs (.focus-config)

### ISSUE THREAD

**Issue by fbjerno** [focus-editor/focus#355]
The ability to use relative paths in [workspace dirs] and in build command settings would allow projects to work regardless of their install directory.

Example:
Starting Focus like this...
![image](https://github.com/focus-editor/focus/assets/75798582/3317060d-b742-4753-aeb2-1e017f5d68c6)
![image](https://github.com/focus-editor/focus/assets/75798582/08348c46-bd31-4e9a-bb60-8c01c4fc9ac8)

I want to be able to specify the "Tge" directory as a workspace dir (relative to the .focus-config) so it will work even if I move the project:
![image](https://github.com/focus-editor/focus/assets/75798582/6271cc0e-a543-498a-a167-04229df2543e)

**Comment by focus-editor** [comment]
I believe this should be working since `0.3.6` - use `.` to refer to the directory in which `.focus-config` is in.

Please reopen if there are issues
