### ISSUE TITLE
Does not compile on MacOS M2 with Jai 0.1.090

### ISSUE THREAD

**Issue by meglio** [focus-editor/focus#365]
<img width="1087" alt="image" src="https://github.com/focus-editor/focus/assets/282177/2d68ccf1-67bc-4ce6-80f5-69c22deca4e2">

Hi, is this expected or needs your attention? -- Thanks.

**Comment by ileonte** [comment]
This is expected - not all of the modules we use support ARM in `0.1.090`. You will still need to run the `x86_64` compiler for now.

**Comment by focus-editor** [comment]
@ileonte if this is expected would you mind modifying the readme to make sure people use the right compiler version?

**Comment by ileonte** [comment]
> @ileonte if this is expected would you mind modifying the readme to make sure people use the right compiler version?

Done: https://github.com/focus-editor/focus/commit/de672c18e27ed0966c0997f8e18dae5c2dfce9e0
