### ISSUE TITLE
Float literals with only one digit before the decimal point are incorrectly highlighted in HLSL

### ISSUE THREAD

**Issue by fbjerno** [focus-editor/focus#367]
**Describe the bug**
Floats are incorrectly highlighted in HLSL.

**To Reproduce**
Create a file with the .hlsl extension and enter a floating point literal with only one digit before the decimal point
(e.g 0.0f or 3.7f). The decimal point and the 'f' at the end are not highlighted as part of the number (the digits before and after the decimal points are recognized as different number literals). I think this is related to a similar bug in the C parser which was fixed in this commit: https://github.com/focus-editor/focus/commit/c80f1fbb7484e236f52c3ff67cc336f60ef69f81

**Expected behavior**
Float literals highlight the decimal point and 'f' suffix.

**Screenshots**
![image](https://github.com/focus-editor/focus/assets/75798582/44824f80-aa8f-41a7-a111-a51fdd3ef6fd)

 - OS: [e.g. Windows]
 - Windows 10
 - Focus Version:
 - 0.3.5

**Comment by focus-editor** [comment]
Should be fixed in the next nightly. Please close the ticket if it all works as expected
