### ISSUE TITLE
Zoom triggers even when scrolling is done

### ISSUE THREAD

**Issue by St0wy** [focus-editor/focus#368]
**Describe the bug**
When I scroll with my trackpad on my laptop, if I press control even after the scroll has stopped, it will zoom. I think the scroll has some kind of inertia, and so when the scroll is "stuck" at the top, pressing control will still pass the scroll event and so trigger the zoom.

**To Reproduce**
1. Use a laptop
2. Open a file that's big enough
3. Scroll quite quickly with the trackpad and have the scroll stop a the tap
4. Quickly press control

**Expected behavior**
For the zoom to not happen when I'm not touching the trackpad. Maybe add a setting to not be able to scroll at all when using control + scroll on a trackpad ? (This is the case on VSCode AFAIK)

 - OS: Windows
 - Focus Version: 0.3.5

**Comment by focus-editor** [comment]
Fixed in #432
