### ISSUE TITLE
V3 -> V4 config migration doesn't preserve theme colors

### ISSUE THREAD

**Issue by fbjerno** [focus-editor/focus#373]
**Describe the bug**
Config version 4 added new options for highlighting code. As far as I can tell these use the default colors rather than grabbing the color that would previously have been used for that type of code from the old config during migration (phew!).

**To Reproduce**
1. Open Focus v0.3.5 the Handmade Hero theme. The theme is displayed correctly.
2. Open the nighly Focus build (0.3.6-dev). The theme is auto-migrated to version 4. Some types of code now use an incorrect color. For these code elements, the color is the same for all migrated themes.

**Expected behavior**
The old colors of the theme are preserved.

**Screenshots**
![image](https://github.com/focus-editor/focus/assets/75798582/c0c80513-33c9-4d57-b397-e0f4dd764c8a)
(left: v3, right: v4, migrated from v3)

 - OS: Windows 10
 - Focus Version: Version 0.3.6-dev (26 May 2024, 00:02:23)

**Comment by focus-editor** [comment]
Thanks for catching this before release! People's configs would be corrupted if we released this. The fix should be in the next nightly.
