### ISSUE TITLE
[Feature Request] Open a file to a line number

### ISSUE THREAD

**Issue by mrjbq7** [focus-editor/focus#376]
Is there a way, or perhaps can we get one, to open a file to a specific line number?

Ideally from the command-line to open into the Focus.app on macOS.

**Comment by focus-editor** [comment]
There's no way to do it when opening, but it's a valid request so we'll do it (but we're busy, so we'll accept a PR if someone does it before we do).

Right now the only way to jump to line is via the go to line dialog on an already open file

**Comment by focus-editor** [comment]
This is done in the latest nightly, will be released with the next release. 

When you pass a path to the executable saying `/path/to/file:<line_number>` should work.

**Comment by mrjbq7** [comment]
Awesome, added support in https://github.com/factor/factor/commit/9d2f151091303622877f5f4e5effbbe71249dbea.

I still have to get our editor integration working with Linux and Windows, will look at that in a bit.
