### ISSUE TITLE
In Open-File navigation, pressing "/" when one of the folders is literally called "/" (root on Mac/Linux) should probably open root rather than the selected folder

### ISSUE THREAD

**Issue by cookednick** [focus-editor/focus#38]
**I don't know. I'm definitely open to debate on this. I just have a sense that this feels wrong.**

I often partially-type folder names then push Enter rather than use the arrow keys (then Enter) to select folders. "/" makes perfect sense as an alternative to Enter.

It is just this one particular case, when the box is blank, on Mac/Linux, the final root folder is always "/". So I find it "inconsistent" when I type "/" and it just selects the first folder, when "/" is a perfect name-match for the last folder in the list.

This could be an exception to the otherwise perfect rule. On Mac/Linux, we could simply select the "/" folder if it is present when that key is pressed. It is also consistent that this is the only time you will ever have this situation occur, so adding a special rule for this one case should not have odd side effects in theory.

![Before pushing "/"](https://github.com/focus-editor/focus/assets/9829045/b3bcac14-821c-4311-941d-fda0b8e71375)

**Comment by cookednick** [comment]
I'll add that if you agree Obiwanus, I'll make this change myself.

**Comment by focus-editor** [comment]
People have reported this already https://github.com/focus-editor/focus/issues/16

I agree that this change should be made.

The tricky part is that `/` is currently bound to `open_directory` in the default configs. If we remove it from there and hard-code it to do `open_directory` only when no path_chunks are present, then people will still have it bound so this will have no effect on them.

But in that case we can just tell them to remove the binding from their configs.

**Comment by cookednick** [comment]
> People have reported this already
Sorry.

>The tricky part...
That OR we continue to have the shortcut be that default, and we simply alter its behavior when these conditions are present (text box is empty & not on Windows) to instead just select the "/" directory. That would probably be the simplest fix code-wise. Just add a branch for that case.

**Comment by focus-editor** [comment]
I don't think that will work but you can try.

**Comment by cookednick** [comment]
Fixed. https://github.com/focus-editor/focus/issues/16#issuecomment-1546821751
