### ISSUE TITLE
Version 0.1.8 shows 0.1.7 on startup screen for Linux

### ISSUE THREAD

**Issue by mathaou** [focus-editor/focus#39]
**Describe the bug**

I downloaded version 0.1.8 for Linux and upon opening the binary was showing that it was version 0.1.7. I double checked and yes I am downloading the correct file. A quick glance at source shows that version 0.1.8 is defined in first.jai or something like that, so I don't know where this stale reference is coming from. Is this a field in some config file somewhere? Most likely user error, but I thought I would report it anyway.

**Comment by ileonte** [comment]
I attached the correct Linux binary to the release, please download the new one (`sha256sum: 85016814671d3c58d5cf3c787242235d28a399018e75c5969decdb7bc1cf4afb`).

**Comment by mathaou** [comment]
Fixed. Thank you.

**Comment by cookednick** [comment]
Thanks for reporting!
