### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by marvhus** [focus-editor/focus#4]
could you add a Linux version with the release binaries?

**Comment by marvhus** [comment]
btw, I got it to kinda work using wine, and a bash script.
But it would still be nice to have a Linux binary.

**Comment by ileonte** [comment]
Here are the usability issues that I'm aware of on the Linux version:

* under X11 there is no mouse wheel support (missing in the `Input` module, I will need to add that)
* under X11 numpad input still seems to be broken (the keys are always interpreted as if NumLock is off, still looking into whether that's a general X11 thing or is just a bug on my setup)
* there is still no save "dialog" of any kind, so if you create a new file there's no way to save it

In terms of generating a binary - it could be done in theory, we would need an old enough version of some distribution (`glibc`) to link against. I don't know if something can be set up on Github to build it automatically or whether I should try and generate a binary manually. Let me know.

**Comment by ileonte** [comment]
Makes sense. I will generate binaries then, we'll work out a way to get them to you to post on Github releases.

**Comment by marvhus** [comment]
@ileonte 
> I don't know if something can be set up on Github to build it automatically or whether I should try and generate a binary manually. Let me know.

You can do that using GitHub actions, though idk if it is possible to do while the compiler isn't public.

**Comment by ileonte** [comment]
I just added a Linux binary to the latest release (`0.1.3`). Please try it out and let me know if it works for you.

**Comment by meglio** [comment]
Is MacOS version even farther than the linux one?

**Comment by marvhus** [comment]
Seams like it doesn't create the Global config, but it does create a example project config, so I just copied and renamed that one as a temporary solution.

Error message:
```
Could not open file "/home/mh/thirdparty/focus/global.focus-config": code 2, No such file or directory
Couldn't read the config file file '/home/mh/thirdparty/focus/global.focus-config'
``

**Comment by marvhus** [comment]
Also, `open projects directory` does nothing.
