### ISSUE TITLE
Editor is stuck when a file dialog opens (Windows)

### ISSUE THREAD

**Issue by ostef** [focus-editor/focus#40]
On Windows, the OS open file dialog that opens when saving a new file causes the editor to not update until the dialog is closed. This leads to confusing situations where it seems the editor is stuck but really it's just that the dialog is still opened behind the editor window. Particularly, resizing the editor window while the dialog is opened breaks the rendering for example.

**Expected behavior**
Ideally the editor should still update normally, without allowing the user to interact with it (window resizes for example should still be reacted to)

- OS: Windows
- Focus Version: 0.1.7

**Comment by focus-editor** [comment]
The save file dialog has been made modal now, which is the intended behaviour. The user is not supposed to be able to interact with the editor until the dialog closes. Thanks for the report.
