### ISSUE TITLE
Error message when staring focus after deleting a file.

### ISSUE THREAD

**Issue by theohogberg** [focus-editor/focus#414]
**Describe the bug**
Error message when staring focus. Cannot exit editor without forcing it (Opt+CMD) on MacOS X 14.5 (23F79).

**To Reproduce**
1. Open a file defined in your workspace using open by name (CMD + P).
2. Delete the content of the file.
3. Exit focus editor (without saving).
4. Try to restart, see error.

**Expected behavior**
I expect to be able to start the editor again without an error message.

**Screenshots**
<img width="257" alt="palla_jakla_wardogs" src="https://github.com/user-attachments/assets/d3d22a9f-e2e8-4c19-84d1-3fc94e80fb3f">

 - OS: [e.g. Windows]
MacOS X 14.5 (23F79)
Focus 0.3.6.1

**Additional context**
M1 MacBook Pro

**Comment by focus-editor** [comment]
Can reproduce, thanks for reporting. This seems to only happen when you close the window using the mouse. For now as a workaround please use the Quit command, which works as it should

**Comment by focus-editor** [comment]
Should be fixed in the next release. Here's a build with the fix https://drive.google.com/file/d/17dHd0pS8QV2rSU5nvwQ2OOf1woCdbHlR/view

Please reopen if there are still issues
