### ISSUE TITLE
Feature request: Disable subpixel antialiasing

### ISSUE THREAD

**Issue by CELLTH** [focus-editor/focus#428]
It would be nice to have the option to disable the subpixel (ClearType/FreeType) anti-aliasing. Even though it looks _good_ in some cases, I prefer to have it off in favor of _normal_ anti-aliasing.

**Comment by focus-editor** [comment]
I'm curious why you prefer normal anti-aliasing? Are there cases where subpixel isn't strictly better for you?

**Comment by focus-editor** [comment]
This is getting closer to the top of the list, so should be done soon hopefully.

> It has always looked worse than normal AA to me, particularly light text on dark backgrounds.
I bought a new monitor yesterday with HDR support, and I noticed that with HDR on + with different monitor modes the text does indeed look bad. But with no HDR and no enhancement it looks good, more crisp than normal AA would.

**Comment by focus-editor** [comment]
This has just been pushed to main, when the next nightly builds you can download and try it https://ileonte.dev/focus-builds/

To disable hinting or subpixel AA set the following in the `[fonts]` section:
```
anti_aliasing: normal  # options: lcd, normal
hinting: false
```

Adding the option of no anti-aliasing is more work that I'm willing to do right now.

Please close the ticket unless there are issues
