### ISSUE TITLE
Feature Request : Line Length on Line Wrap

### ISSUE THREAD

**Issue by csimo29** [focus-editor/focus#439]
It would be nice to set a line character length for the line wrapping within global config, or within the projects. I often take .txt notes with focus and would enjoy narrower columns when writing paragraphs without having to make my window narrow or open another buffer and resize it manually. 

line_wrap_is_on_by_default:             true
line_wrap_set_line_length:               120  # some way to change it

**Comment by focus-editor** [comment]
Would changing max editor width help? I always use it because when there's
just one editor open it's too wide

**Comment by csimo29** [comment]
this works perfectly! thanks!
