### ISSUE TITLE
Odd crash report.

### ISSUE THREAD

**Issue by CELLTH** [focus-editor/focus#455]
I experienced an odd crash on nightly build 33400670bd85be014b13f183a76ebece5f885234 when I executed one of my build commands. Focus produced the following crash report:

```
Array bounds check failed in file z:/build/src/build_system.jai at line number 513: 
Provided index: 11, maximum index: 10

Stack trace not available (it was lost due to a #no_context call).
```

I couldn't re-reproduce this but I'm posting it here in case other people encounter similar crash.
The crash happened when I executed the second build command while on the main menu. With no buffers open.
Here is my build config: 
```
[[build commands]]
build_working_dir           C:\build\path
open_panel_on_build         true
error_regex                 ^(?P<file>.*)\((?P<line>\d+),(?P<col>\d+)\): (?P<type>error|warning) (?P<msg>.*)$

auto_jump_to_error          false

[build]
build_command               build.bat
key_binding                 Alt-1

[build_full]
build_command               build.bat full
key_binding                 Alt-2
```

**Comment by focus-editor** [comment]
Thanks for the report. This gives enough information to debug, we'll revisit this code and try to make it more robust

**Comment by focus-editor** [comment]
Should hopefully be fixed
