### ISSUE TITLE
Printing too fast crashes focus 

### ISSUE THREAD

**Issue by o-numina** [focus-editor/focus#456]
When printing too fast to the console focus crashes.
vcruntime140.dll throws the exception 0xc0000005: access violation reading location 0xFFFFFFFFFFFFFFFF

Example code to reproduce the problem:
```c
#include <stdio.h>

int main()
{
   for (;;)
   {
      printf("Hello world!");
   }
}
```
 
 Sleeping for 1 ms does not crash the application.
 ```c
#include <stdio.h>
#include <Windows.h>

int main()
{
   for (;;)
   {
      Sleep(1);
      printf("Hello world!");
   }
}
```

 - OS: Windows 11
 - Focus Version: Version 0.3.7-527464a

**Comment by focus-editor** [comment]
This should be fixed in the main branch.

If you let it print for some time then it will crash when trying to stop the command, but that's a separate error, it will be fixed soon
