### ISSUE TITLE
Crash when duplicating editor

### ISSUE THREAD

**Issue by ostef** [focus-editor/focus#473]
Focus crashed when duplicating an editor while already in split mode. Fortunately I had built the editor in debug mode so I got the stack trace. I don't think there is any chance that my changes caused this crash, I only added very simple timer profiling that reports blocks of code that take a long time to execute for issue https://github.com/focus-editor/focus/issues/472
```
The program crashed because of an access violation reading location 0x150db4e0e18.

Printing the stack trace:
handle_exception                  C:\Programs\jai\modules\Runtime_Support_Crash_Handler.jai:361
... (skipping OS-internal procedures)
duplicate_active_editor           C:\Users\Stefan\Documents\focus-main\src\editors.jai:1994
switch_to_editor                  C:\Users\Stefan\Documents\focus-main\src\editors.jai:1966
active_editor_handle_event        C:\Users\Stefan\Documents\focus-main\src\editors.jai:202
editors_handle_event              C:\Users\Stefan\Documents\focus-main\src\editors.jai:15
main                              C:\Users\Stefan\Documents\focus-main\src\main.jai:309
```

OS: Windows 10
Version: 0.3.7-dev

**Comment by focus-editor** [comment]
Would you be able to point to the line you have at `editors.jai:1994`? In my code it's shifted
