### ISSUE TITLE
Copying from focus causes Chrome to crash

### ISSUE THREAD

**Issue by bugthug** [focus-editor/focus#55]
**Describe the bug**
Copying a section of the provided `program.c` file causes crashes in Chrome and Focus, and not working in any other program.

**To Reproduce**
1. Download [program.zip](https://github.com/focus-editor/focus/files/11645409/program.zip) and extract `program.c`
2. Press `Alt+x`, then `Navigate To File From Root` until you reach the file.
3. Copy from the following section (yes I am aware I did not intialize curses):
```C
#include <stdio.h>
#include <unistd.h>
#include <curses.h>

int main() {
    cbreak();
    echo();
    int value;
    scanf("%d", &value);
    return 0;
}
```
4. Paste in any other program
5. Program stops responding/doesn't read input, upon pasting in focus, focus stops responding.

**Expected behavior**
Copied text is handled correctly and does not cause crashes. 

**Screenshots**
My pc is not in English so any screenshots might be confusing. Anyways, I don't think any visual aid is needed. I can provide if you want, though.

 - OS: Fedora 38
- Wayland
 - Focus Version: 0.1.9

**Additional context**
I have set the environment variable `FOCUS_LD_BACKEND` to `Wayland`

**Comment by focus-editor** [comment]
Seems to be a Linux-only thing because on Windows I can't reproduce it. @ileonte - would you please have a look when you have a moment? Thanks

**Comment by cookednick** [comment]
Works on Mac

**Comment by ileonte** [comment]
Works fine for me on both `0.1.9` and `0.1.10`. I'm going to set up a Fedora VM to see if I can reproduce on that.

**Comment by bugthug** [comment]
> Works fine for me on both `0.1.9` and `0.1.10`. I'm going to set up a Fedora VM to see if I can reproduce on that.

Just make sure to try copying not just this snippet. This bug is extremely annoying, very frequent when copying but also unpredictable (at least to me). Maybe use the vm a bit for editing, too

**Comment by ileonte** [comment]
I still don't see this issue on any of my systems. Please retry with the latest nightly and reopen if it's still happening.
