### ISSUE TITLE
High CPU use when editor is used for some time

### ISSUE THREAD

**Issue by rarsp** [focus-editor/focus#58]
Minimize editor, do something else for some time (in my case use Unity editor), go back to Focus editor and it has very high CPU use that is unusable.

It happened twice in such circumstances but it's hard for me to reproduce it freely, so it might not be related to minimizing application but some other OS behaviour?

EDIT: looks like I can reproduce it by just using editor for some time and it might be related with C# files support.

- Editing C# files

 - OS: Windows 10
![focus](https://github.com/focus-editor/focus/assets/47478055/e61fc45d-f25e-4722-9540-afbd174af85a)

**Comment by focus-editor** [comment]
Thanks, will investigate. 

@audV have you noticed anything like this when editing C# files?

**Comment by audV** [comment]
I don't actually do much C# editing. I didn't notice anything during testing C# files during development of the highlighter for it. I had a try at replicating(on Win 10 as well) but no result(I don't have Unity installed).

I had look at the loops in the C# highlighter but couldn't see anything that might not terminate unless max_t was set incorrectly.

**Comment by rarsp** [comment]
C# is not a problem. 

Now I am suspecting that it could be caused by having windows line endings in some files.

**Comment by cookednick** [comment]
> Now I am suspecting that it could be caused by having windows line endings in some files.
When you save a file in Focus, these should get stripped, so if you continually run into this problem, that should not be it unless you reintroduce those line endings in some other program regularly.

**Comment by focus-editor** [comment]
I haven't had a chance to look into it yet, but I don't see how windows line endings would cause the CPU usage to be high.

**Comment by rarsp** [comment]
I happens everytime when a long file (few k loc) with windows line endings CR/LF is open

**Comment by rarsp** [comment]
Looks like I can reproduce it.
FYI I am editing C# files.

It happens when I am using Search in Workspace, after that CPU use increases gradually to the point that it lags my computer.


I also reproduce it by using this repo: https://github.com/IceReaper/DoomEngine
It's C# port of Doom with some big files in it

**Comment by ivan-cx** [comment]
It could be related (or not): on Linux I get 8-9% CPU usage from the start without opening any file:
![image](https://github.com/focus-editor/focus/assets/57104205/8f7076a3-a15c-4424-9f11-065d7a314247)
(the Firefox plays a youtube video at the same time)

**Comment by focus-editor** [comment]
I couldn't reproduce it still. If maybe one of you could run a debug build in a sampling profiler when this happens it would be very helpful.

**Comment by rarsp** [comment]
With Intel HD card CPU use is growing very slowly and I think it never reaches 7% at peak, but it lags my mouse when cursor is in the bottom left corner of the screen.

With NVidia card it reaches very fast 25% of CPU use (full 1 core).

Also it seems editor is much more snappy on Intel HD card.

Issue with graphic card drivers?

**Comment by ivan-cx** [comment]
@focus-editor here is several seconds of initial screen on Linux, not opening any files and not counting application startup:
![image](https://github.com/focus-editor/focus/assets/57104205/ce12bf3d-774d-4741-a229-d22327961f4f)
![image](https://github.com/focus-editor/focus/assets/57104205/7de0ff62-e1db-49f0-8c90-b4c9a94e85b0)

700k calls to array_add seem suspicious

**Comment by focus-editor** [comment]
When you start Focus it will scan the whole workspace and open every text file in that workspace in the background, which is what you're seeing.

If you start on a fresh workspace with no folders in it it won't do that.

**Comment by ivan-cx** [comment]
How long should it take to scan? 
CPU activity does not stop in couple of minutes.
And activity is the same if I comment all workspace directories in /.config/focus-editor/global.focus-config

**Comment by focus-editor** [comment]
Can you please do another profile with an empty workspace?

**Comment by ivan-cx** [comment]
This is a capture of the first clean launch of the focus_debug ( 9bb4de8 ), no configs existed before the launch at all. Built with beta 0.1.069.

I've waited several seconds after launch, then captured 2-3 seconds with profiler, then stopped. So it literally did nothing this time, no scanning of files, etc. Just some mouse input I guess?

![Screenshot from 2023-06-28 12-19-10](https://github.com/focus-editor/focus/assets/57104205/9b8ce075-380c-4ede-96d1-31697ef71bc3)

 CPU usage with profiler is 2X higher because of the profiler overhead. Without profiler I get the same 7-9% on my laptop.

**Comment by fbjerno** [comment]
I also have this issue. Focus usually uses 0% CPU in the background, but sometimes after having it running in the background for a long time, the CPU usage will increase, hovering between 10 - 20% and making my cursor + OS stuttery (on Windows 10).

**Comment by diimdeep** [comment]
macOS 11.7, 2013 mbpr, Intel HD
It is constant 13% CPU without opening any files, hidden or not, or after opening simple file, it is the same.
With Quartz Debug.app -> Flash screen updates, I can see there is no redraws, must be something else then..

![Screenshot 2024-01-02 at 5 51 46 PM](https://github.com/focus-editor/focus/assets/485713/74b82486-fb52-48a6-9a20-88907bf9be4d)

**Comment by obiwanus** [comment]
@diimdeep macos is the least developed port right now, the app is constantly being rendered without waiting for input.
We will accept PRs which fix this.

**Comment by JesseRMeyer** [comment]
On Win10 on NV3060, simply _moving the mouse_ over a Focus 0.3.1 window will cause high cpu and gpu %, despite no pixels changing nor a need to re-draw the screen.

**Comment by obiwanus** [comment]
@JesseRMeyer that's expected because it's using immediate gui. We have to redraw in order to see whether something has changed. Maybe we'll tweak it someday but it's low priority

**Comment by focus-editor** [comment]
There haven't been any complaints about this for a while. 
There was some work done with OpenGL which was causing issues on some systems.
The mac situation has also been improved. 
Please create another issue if there are still problems.
