### ISSUE TITLE
feature: tabs

### ISSUE THREAD

**Issue by ryuukk** [focus-editor/focus#69]
Not a bug, but a feature suggestion

I would like to see tabs added

Why? it's part of my workflow, i like setting context trough tabs when i'm working on something instead of constantly switching buffers and typing file names, it's a waste of time

**Comment by focus-editor** [comment]
Sorry to see you go.

We have to draw the line somewhere in terms of features that are acceptable so unfortunately some feature requests will have to be turned down.
