### ISSUE TITLE
Animation problems with history

### ISSUE THREAD

**Issue by hfr4** [focus-editor/focus#71]
**Describe the bug**
1. When undoing the history, if a file was opened on the left the reopening animation is in the wrong direction
2. There also isn't any animation when the moving back in the history close a panel.

**To Reproduce**
1. Open a file
2. Open another file on the left
3. Close the left file
4. Undo history

**Screenshots**
![2](https://github.com/focus-editor/focus/assets/30574115/f8124dc9-af68-4600-b11a-ea515ec5c768)

 **Focus Version**
0.1.10

**Comment by focus-editor** [comment]
Should be fixed now https://github.com/focus-editor/focus/commit/be763f4c3ed185532b5f329ba6b4b295c10bcbae
