### ISSUE TITLE
Crash after history manipulation

### ISSUE THREAD

**Issue by hfr4** [focus-editor/focus#73]
**Describe the bug**
Crash after history manipulation

**To Reproduce**
1. Open a buffer
2. Duplicate it to the right using "duplicate_editor" shortcut
3. Close the left one using "close_other_editor" shortcut
4. Move back history using "move_to_previous_editor_history" shortcut
    => the left panel doesn't reopen
5. Move back history another time
6. Move cursor anywhere on the editor
7. Move back history
8. Move cursor anywhere on the editor
    => Crash

**Expected behavior**
Should open the left buffer on step 4 and not crash :)

**Screenshots**
![1](https://github.com/focus-editor/focus/assets/30574115/a2c2b574-ea35-4b35-bdd3-f1bf85c90bef)

**Version**
0.1.10

**Comment by focus-editor** [comment]
Should be fixed now https://github.com/focus-editor/focus/commit/be763f4c3ed185532b5f329ba6b4b295c10bcbae
