### ISSUE TITLE
Wrong active panel switching with history

### ISSUE THREAD

**Issue by hfr4** [focus-editor/focus#74]
**Describe the bug**
When closing the right panel using "close_other_editor" shortcut then moving to previous history, the active panel switch side

**To Reproduce**
1. Open a file
2. Dupicate to the right using "duplicate_editor" shortcut
3. Make the left editor active
4. Close right editor using "close_other_editor" shortcut
5. Go to previous history using "move_to_previous_editor_history" shortcut
   => The active panel is now the right one

**Expected behavior**
Since we closed the right panel with the left panel active in step 4. , the left panel should still be the one active in step 5.

**Screenshots**
![1](https://github.com/focus-editor/focus/assets/30574115/0bef46a9-0c4e-474b-9e18-1ce1d6c4441a)

**Version**
0.1.10

**Comment by focus-editor** [comment]
Yes the history is a bit broken, I need to take a look at it.

Sorry I'm sick and can't get back to you on the other stuff yet - will do
when I can.

**Comment by focus-editor** [comment]
Should be fixed now https://github.com/focus-editor/focus/commit/be763f4c3ed185532b5f329ba6b4b295c10bcbae
