### ISSUE TITLE
Focus editor crashes on files larger than 2GB

### ISSUE THREAD

**Issue by Yersh** [focus-editor/focus#81]
I'm using focus 0.1.10 on windows 10.

I tried to open 2GB csv file.
`test2310722_.csv` (exact size is 2 152 105 405 bytes)
focus editor crashed with error:
`
Array bounds check failed in file W:/focus/src/buffer.jai at line number 111: 
Provided index: -2147483335, maximum index: 2147483961
`

When I tried to open slightly smaller file
`test2310720.csv` (exact size os 2 152 103 659 bytes)
Everything worked fine.

**Comment by focus-editor** [comment]
I'm sorry, this is one of the limitations of the editor - it's even written in the readme. It is not designed to open very large files. Even tens of megabytes for a text file would be too much for this editor. This is a design decision that was planned from the start.

**Comment by focus-editor** [comment]
On second thought, we should just refuse to load files larger than some size. We could use this issue to track that work.

**Comment by Yersh** [comment]
That's sad if you keep this desgn limitation. Because on 1-2GB files focus works faster than any text editor I've ever seen.

**Comment by focus-editor** [comment]
By "works faster" what exactly do you mean? I find it hard to believe it opens 1GB files and you're able to edit it without massive frame drops - due to the choice of data structures.

**Comment by Yersh** [comment]
well.
vscode crashes on this file even after removing memory limitation.
sublime takes 1 minute to open it, but renders like 1 frame per 30 seconds during scrolling (it's like 0.033 fps or something)
bunch of other windows editors either crash or plain refuse to open big files.

Before Focus I had to use trial version of some obscure proprietery editor, which advertised "very big file support".   

Focus opens file in 5 seconds and scrolls no problem.
editing is laggy, but I mostly copy paste whole line from such big files, so it's not a problem.
The only downside that search doesn't work, since it tries to find the string while you typing, which doesn't work on such a big file.

**Comment by focus-editor** [comment]
That's interesting.

The reason it doesn't open files larger than 2GB is because signed 32 bit integers were chosen for indices and byte offsets within buffer. The fix would be to use 64 bit integers, but I wouldn't want to do it for everyone, because 99.99% of people never need it but they would pay the price of larger data structures.

We could make it possible to enable s64 at compile time, but it would have to wait because there's a a lot of work that has been in the queue for a while. If you have access to jai you could  do it.

**Comment by focus-editor** [comment]
It's not a simple change, it would require a lot of careful replacing. We'll try it at some point, but right now there's bigger fish to fry

**Comment by focus-editor** [comment]
We're focusing on smaller files for now. There's just too many things that are more important.
The latest version of the editor shouldn't crash when attempting to open files larger than 2GB, but instead show an error.
