### ISSUE TITLE
Feature Request: Compilation

### ISSUE THREAD

**Issue by Sl3dge78** [focus-editor/focus#86]
It's one thing that I love in vim, emacs, 4coder, and to some extent VSCode : 
- Run a project specific command inside the editor
- It grabs output and prints it to a buffer
- Creates links to the reported error locations

I'd be happy to try working on this but I might take a lot of time as I'm not super familiar with the codebase yet.
Let me know if you think this is a good idea and if my suggested flow fits within your vision.

**Comment by focus-editor** [comment]
The implementation of this is already done by @Jakob, it's been waiting for
me to review it and incorporate into the editor.

Parsing errors isn't done yet, but we'll do it
