### ISSUE TITLE
Numpad keys in shortcuts

### ISSUE THREAD

**Issue by Roman-Skabin** [focus-editor/focus#9]
Can you please add the ability to map numpad keys? I just used to some shortcuts like ctrl+numpad4 and ctrl+numpad6 to switch between left and right editor 🙂
\
\
\----------------
Version: 0.1.4

**Comment by focus-editor** [comment]
This is currently not the easiest thing to do, which requires the Input module modification - I don't want to do it until it's clear what changes will be made to the Input module by Thekla, so this is temporarily on hold.

**Comment by ileonte** [comment]
This should be fixed in the next release (`0.2.1`). Until then you can grab a nightly build:
* https://ileonte.dev/focus-builds/Windows/nightly/focus-nightly-a36257d.exe
* https://ileonte.dev/focus-builds/Linux/nightly/focus-linux-nightly-a36257d

**Comment by Roman-Skabin** [comment]
Since it's done I think we can close it?
