### ISSUE TITLE
macOs: Focus doesn't exit fully and prevents shutdown

### ISSUE THREAD

**Issue by mzzovko** [focus-editor/focus#90]
**Describe the bug**
MacOs: Focus doesn't exit fully and prevents shutdown when trying to create a new file without a project opened

**To Reproduce** 
On macOS (video is below)
1. Open Focus
2. press `shift + cmd + p` 
3. select `Create new file`
4. type something
5. press `CMD + S`
7. press macOs quit app button

**Expected behavior**
- I expect that CMD + S will save file - but nothing happens or something happens - but it's not clear what 
- I expect that macOs exit button will shutdown app completely
- I expect that Focus doesn't prevent shutdown of my OS

**Screenshots**
https://github.com/focus-editor/focus/assets/9343781/5b05f82f-cc42-429a-8bb6-287f19338973

I feel like this is a symptom of some other underlying problem - how stuff is released from use somewhere

**Comment by cookednick** [comment]
Thanks for the submission. This is a known bug and I intentionally left it sitting around, but it's good to have it documented here.

> I expect that CMD + S will save file - but nothing happens or something happens - but it's not clear what
It currently does nothing. I couldn't find a simple way to bring up the Finder dialog for saving a file from Jai. We also already have plans to write our own cross-platform equivalent. When that's done, saving a new file will work on Mac. Until then, it is a missing feature.

> I expect that macOs exit button will shutdown app completely
I agree. I will look into this.

> I expect that Focus doesn't prevent shutdown of my OS
Are you talking about (A) how when you close the window it can't be quit? Or are you saying when (B) there are unsaved files, you would expect system shutdown to prompt you about the unsaved files?

For the last one, as a workaround, Cmd+Option+Escape is the shortcut to Force Quit apps that cannot be closed. Sorry about that.

**Comment by focus-editor** [comment]
I believe it's somewhat improved, but there's still an issue with closing by clicking on the close button in the titlebar - #470
