### ISSUE TITLE
Incorrect behaviour of selection on MacOS

### ISSUE THREAD

**Issue by Roman-Skabin** [focus-editor/focus#95]
**Describe the bug**
Incorrect behaviour of Cmd-Shift-ArrowLeft/Right on MacOS

**To Reproduce**
1. Map Cmd-ArrowLeft to move_left_by_word_ends and Cmd-ArrowRight to move_right_by_word_ends
2. Try to use Cmd-Shift-ArrowLeft/Right to select a word.
3. Selection extends to the beginning/end of the line just like if you would use jump_to_line_start/end + Shift.

**Expected behavior**
Only one word should be selected.

- OS: MacOS Ventura 13.4.1
- Focus Version: 0.1.10

**Comment by focus-editor** [comment]
If you use the development version of the editor this problem should go away. The way config files are handled have changed in a breaking way - they no longer fall back to the default config. Which means that you will only get the keybinds that are explicitly specified in the global config.

**Comment by Roman-Skabin** [comment]
No, I'm using binaries from Releases. I'm not building editor by myself.
Ok, I'll try HEAD

**Comment by Roman-Skabin** [comment]
On HEAD selection does not work at all

**Comment by focus-editor** [comment]
My guess is that you bound `Cmd-ArrowRight` to `move_right_by_word_ends` and then trying to fire this action by pressing `Shift-Cmd-ArrowRight`.

If that's the case then it won't work, yes, because that would be a different combination. You would need to either specify both combos explicitly like this:
```
Cmd-ArrowRight                  move_right_by_word_ends
Shift-Cmd-ArrowRight         move_right_by_word_ends
```

Or use a shortcut, which means the same thing:

```
{Shift}-Cmd-ArrowRight    move_right_by_word_ends
```

**Comment by focus-editor** [comment]
I would recommend that you use a fresh config if you do use the dev version of the editor to avoid other issues.

We want to have a config rewrite system, and that's why there's no new release yet, because it's tricky and isn't yet done.

**Comment by Roman-Skabin** [comment]
Oh, I see, with {Shift} it works.
I thought {Shift} is just an optional key in shortcut and it does not mean that it will allow me to use selections with shortcut.

**Comment by focus-editor** [comment]
The meaning of shift is hard-coded in the editor. Yes, `{shift}` is just a convenient way to specify bindings that support selection. We weren't trying to make it super general and allow anything else play the role of Shift - that would probably be messy and not needed.
