### ISSUE TITLE
Focus: Focus.exe - Bad Image

### ISSUE THREAD

**Issue by syaoransan** [focus-editor/focus#96]
**Describe the bug**
C:\Windows\system32\atig6txx.dll is either not designed to run on windows or it contains an error.
Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f.

**To Reproduce**
Just try to run the app. The projects folder and config file will be created, the app will run just fine, it just the error message will pop up at the beginning everytime trying to run the app.

**Expected behavior**
No error message pop up when running the app.

OS: [Windows]
Windows 10 Pro 22h2 (OS Build 19045.3086)
focus version 0.1.10

**Screenshot**
![focus error](https://github.com/focus-editor/focus/assets/78855146/32332634-8d40-4614-bdad-fa12cb22e613)

**Comment by focus-editor** [comment]
Seems like a problem with GPU drivers - please can you try updating them
first?

**Comment by syaoransan** [comment]
Thanks it works
