### ISSUE TITLE
Clicking on text adds more cursors instead of moving the cursor

### ISSUE THREAD

**Issue by Silnar** [focus-editor/focus#98]
**Describe the bug**
On Mac, from time to time, especially after coming to focus editor from another app
clicking on text adds new cursors instead of moving the cursor.

It behaves like Cmd key was pressed whereas it isn't.

**To Reproduce**
1. Switch to another app (perhaps located on another workspace) using Cmd+Tab.
2. Come back to Focus editor using Cmd+Tab.
3. Click on text to move the cursor to a new position.
4. See that a new cursor is added instead.

**Expected behavior**
Clicking on text should always move the cursor to the new position.

- OS: MacOs (Ventura 13.4, Apple M1)
- Focus Version: 0.1.10

**Comment by focus-editor** [comment]
This is fixed in the development branch, hopefully it won't be too long before the next release.

**Comment by focus-editor** [comment]
This should be fixed in `0.2.0` - please reopen if the issue persists
