### ISSUE TITLE
The editor crashes at seemingly random times

### ISSUE THREAD

**Issue by ostef** [focus-editor/focus#99]
The editor crashes at seemingly random times.

This has happened to me a significant number of times when doing different kinds of things (typing, pasting, undoing, saving)

After compiling the editor in debug mode with the Jai 0.1.0709 compiler (this happened before using the released binary), I was able to see the stack trace, and it shows me that this is a crash happening in the Default_Allocator when allocating small blocks of memory:

The program crashed because of an access violation reading location 0x1ab0000177e.

Printing the stack trace:
handle_exception                  d:\jai\modules\Runtime_Support_Crash_Handler.jai:364
... (skipping OS-internal procedures)
free_list_pop                     d:\jai\modules\Default_Allocator\module.jai:1311
allocate_small                    d:\jai\modules\Default_Allocator\module.jai:1378
allocate                          d:\jai\modules\Default_Allocator\module.jai:1483
allocator_proc                    d:\jai\modules\Default_Allocator\module.jai:38
__default_allocator_proc          d:\jai\modules\Preload.jai:391
alloc                             d:\jai\modules\Basic\module.jai:93
alloc_string                      d:\jai\modules\Basic\module.jai:147
copy_string                       d:\jai\modules\Basic\Simple_String.jai:107
new_replace_edit                  D:\dev\focus-0.1.10\src\buffer.jai:753
replace_range                     D:\dev\focus-0.1.10\src\buffer.jai:51
paste_from_clipboard              D:\dev\focus-0.1.10\src\editors.jai:2247
active_editor_handle_event        D:\dev\focus-0.1.10\src\editors.jai:207
editors_handle_event              D:\dev\focus-0.1.10\src\editors.jai:13
main                              D:\dev\focus-0.1.10\src\main.jai:228

I have came across different cases of the default allocator failing when allocating small blocks of memory. If after investigation it turns out this is not a problem with Focus but a bug in the Default_Allocator, we should send a bug report to the Jai team.

 - OS: Windows 10
 - Focus Version: 0.1.10 (compiled in debug with Jai 0.1.0709)

**Comment by focus-editor** [comment]
It's weird.

I've hit a couple of crashes and tried to catch them by running the editor
in debugger all the time. After that I've never hit a crash. I do remember
seeing a similar traceback though and wondering what the hell is going on.

I'll need to think about it some more. It might be a bug outside focus but
hopefully not

**Comment by focus-editor** [comment]
As @onelivesleft mentioned, it could be because we're allocating in one thread and freeing in another.

When the editor starts, it creates a bunch of buffers in a bunch of threads, which involves allocation. This has been the case from the first version of the editor. Later when modifying those buffers in the main thread we might reallocate and free some stuff.

If this is indeed the reason why it's failing, I don't see why it's not crashing on literally every keystroke.
@onelivesleft  - do you have an idea? See `directory_scan_threadproc` for the function which allocates in a thread.

**Comment by onelivesleft** [comment]
The default allocator should be able to free across threads fine (it even has a test to check this).  It's possible it has a bug, but more likely is focus is messing up cross-thread in some way.  The way you're using Thread_Group isn't how I would expect it to be used: if I was using it I would make  a single Thread_Group (with threads = processors), and pass it work in a struct like
```
Thread_Work :: struct {
    work_type : enum { directory_scan; file_search; }
}

Director_Scan_Work :: struct {
    using #as base: Thread_Work;
    // ... directory scan data
}
```

thread_work_proc :: (...) {
    thread_work := cast(*Thread_Work)data;
   if thread_work.work_type == {
       case .directory_scan;
   //...
```

**Comment by focus-editor** [comment]
I agree that would simplify things - will look into it and see if I that gives me an idea of what I might be doing wrong.

**Comment by onelivesleft** [comment]
I've updated my main.jai like this: ```

main :: () {
    #if DEBUG {
        UA :: #import "Unmapping_Allocator";
        context.allocator = UA.get_unmapping_allocator();
    }
```
```
#import "Basic"()(MEMORY_DEBUGGER=DEBUG);
```
(The bottom one has already snagged me an erroneous free)

**Comment by focus-editor** [comment]
Where's the erroneous free? I've tried the same but got nothing.

**Comment by onelivesleft** [comment]
It was in my fork, not one you need to worry about.

**Comment by focus-editor** [comment]
@onelivesleft switching to rpmalloc does seem to fix the problem, at least in the few test runs that I did.

Finally a sort-of consistent repro of this problem that worked for me was:

1. Open .added_strings_w3.jai
2. Start creating cursors below (Alt-Shift-Down by default)
3. It crashes consistently from within the default allocator
4. Switch to rpmalloc and repeat the steps
5. No crashes

Of course it might mean the problem is just masked somehow, but still.

**Comment by focus-editor** [comment]
Unfortunately I hit the same issue with rpmalloc 

![image](https://github.com/focus-editor/focus/assets/119373822/b9a8fa95-2711-4ee8-aed2-e5fb4cd76463)

**Comment by onelivesleft** [comment]
Adding lots of cursors to added strings crashes regardless of the allocator used

**Comment by focus-editor** [comment]
@ostef please test with the most current version, the problem might've been fixed or at least alleviated

**Comment by ostef** [comment]
@focus-editor will do

**Comment by focus-editor** [comment]
I haven't had a crash for a long time, must've been fixed. Please reopen if it happens again
